// Package graph implements the document generation pipeline as an Eino compose.Graph,
// following the official "Graph as Agent Tool" architecture.
// Reference: https://www.cloudwego.io/docs/eino/overview/graph_or_agent/
package graph

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"
	"time"

	tradeModels "candypro/api/internal/models/trade"
	einotool "candypro/api/internal/pkg/eino/tool"

	"github.com/cloudwego/eino/compose"
	"gorm.io/datatypes"
)

// DocGenerationInput defines the structured input for the document generation pipeline.
type DocGenerationInput struct {
	TradeID       uint     `json:"trade_id"`
	DocTypes      []string `json:"doc_types"` // e.g. ["PROFORMA_INVOICE", "COMMERCIAL_INVOICE"]
	BuyerName     string   `json:"buyer_name,omitempty"`
	SellerName    string   `json:"seller_name,omitempty"`
	Incoterms     string   `json:"incoterms,omitempty"`
	PaymentTerms  string   `json:"payment_terms,omitempty"`
	TotalAmount   float64  `json:"total_amount,omitempty"`
	Currency      string   `json:"currency,omitempty"`
	ExtraContext  string   `json:"extra_context,omitempty"`
}

// DocGenerationOutput contains results from the document generation pipeline.
type DocGenerationOutput struct {
	Status       string              `json:"status"`
	GeneratedDocs []GeneratedDocInfo `json:"generated_docs"`
	Summary      string              `json:"summary"`
	Errors       []string            `json:"errors,omitempty"`
}

// GeneratedDocInfo describes a single document generated by the pipeline.
type GeneratedDocInfo struct {
	DocType   string `json:"doc_type"`
	DocNumber string `json:"doc_number"`
	Content   string `json:"content"`
}

// pipelineState is passed between graph nodes via compose.State.
type pipelineState struct {
	Input    DocGenerationInput
	Docs     []GeneratedDocInfo
	Errors   []string
	Persister einotool.DocumentPersister
}

// NewDocumentPipelineGraph builds a deterministic compose.Graph that generates
// trade documents in sequence. This graph is intended to be wrapped as a Tool
// and registered with the TradeAssistant ChatModelAgent.
//
// Architecture per official Eino guide:
//
//	Agent (LLM decision) → calls "generate_trade_documents" tool
//	  └── Graph: PrepareContext → GenerateDocs → PersistDocs
func NewDocumentPipelineGraph(ctx context.Context, persister einotool.DocumentPersister) (*compose.Graph[DocGenerationInput, DocGenerationOutput], error) {
	graph := compose.NewGraph[DocGenerationInput, DocGenerationOutput]()

	// Node 1: PrepareContext — validates input, sets defaults
	if err := graph.AddLambdaNode("PrepareContext", compose.InvokableLambda(
		func(ctx context.Context, input DocGenerationInput) (output pipelineState, err error) {
			if input.TradeID == 0 {
				return output, fmt.Errorf("trade_id is required")
			}
			if len(input.DocTypes) == 0 {
				// Default: generate all essential documents
				input.DocTypes = []string{
					tradeModels.DocTypeProformaInvoice,
					tradeModels.DocTypeCommercialInvoice,
					tradeModels.DocTypePackingList,
					tradeModels.DocTypeSalesContract,
				}
			}
			if input.SellerName == "" {
				input.SellerName = "CandyPro OEM"
			}
			if input.Incoterms == "" {
				input.Incoterms = "FOB Shanghai"
			}
			if input.Currency == "" {
				input.Currency = "USD"
			}
			return pipelineState{Input: input, Persister: persister}, nil
		},
	)); err != nil {
		return nil, fmt.Errorf("PrepareContext node: %w", err)
	}

	// Node 2: GenerateDocs — iterates doc types and generates content
	if err := graph.AddLambdaNode("GenerateDocs", compose.InvokableLambda(
		func(ctx context.Context, state pipelineState) (pipelineState, error) {
			for _, docType := range state.Input.DocTypes {
				doc, err := generateDocument(ctx, docType, state.Input)
				if err != nil {
					log.Printf("Graph: generate %s failed: %v", docType, err)
					state.Errors = append(state.Errors, fmt.Sprintf("%s: %v", docType, err))
					continue
				}
				state.Docs = append(state.Docs, doc)
			}
			return state, nil
		},
	)); err != nil {
		return nil, fmt.Errorf("GenerateDocs node: %w", err)
	}

	// Node 3: PersistDocs — saves generated documents to DB
	if err := graph.AddLambdaNode("PersistDocs", compose.InvokableLambda(
		func(ctx context.Context, state pipelineState) (pipelineState, error) {
			if state.Persister == nil {
				state.Errors = append(state.Errors, "persister is nil, documents not saved to DB")
				return state, nil
			}
			for _, doc := range state.Docs {
				tradeDoc := &tradeModels.TradeDocument{
					TransactionID: state.Input.TradeID,
					Type:          doc.DocType,
					DocNumber:     doc.DocNumber,
					Status:        tradeModels.TradeStatusDraft,
					IsAIGenerated: true,
					LineageSource: "ai_draft_graph",
				}
				if err := json.Unmarshal([]byte(doc.Content), &tradeDoc.Content); err != nil {
					tradeDoc.Content = datatypes.JSON([]byte(doc.Content))
				}
				if err := state.Persister.AddDocument(ctx, tradeDoc); err != nil {
					state.Errors = append(state.Errors, fmt.Sprintf("persist %s: %v", doc.DocType, err))
				}
			}
			return state, nil
		},
	)); err != nil {
		return nil, fmt.Errorf("PersistDocs node: %w", err)
	}

	// Node 4: BuildOutput — constructs the final output
	if err := graph.AddLambdaNode("BuildOutput", compose.InvokableLambda(
		func(ctx context.Context, state pipelineState) (DocGenerationOutput, error) {
			status := "completed"
			if len(state.Errors) > 0 && len(state.Docs) == 0 {
				status = "failed"
			} else if len(state.Errors) > 0 {
				status = "partial"
			}

			summary := fmt.Sprintf("Generated %d document(s)", len(state.Docs))
			if len(state.Errors) > 0 {
				summary += fmt.Sprintf(" with %d error(s)", len(state.Errors))
			}

			return DocGenerationOutput{
				Status:        status,
				GeneratedDocs:  state.Docs,
				Summary:       summary,
				Errors:        state.Errors,
			}, nil
		},
	)); err != nil {
		return nil, fmt.Errorf("BuildOutput node: %w", err)
	}

	// Wire the graph: START → PrepareContext → GenerateDocs → PersistDocs → BuildOutput → END
	_ = graph.AddEdge(compose.START, "PrepareContext")
	_ = graph.AddEdge("PrepareContext", "GenerateDocs")
	_ = graph.AddEdge("GenerateDocs", "PersistDocs")
	_ = graph.AddEdge("PersistDocs", "BuildOutput")
	_ = graph.AddEdge("BuildOutput", compose.END)

	return graph, nil
}

func generateDocument(_ context.Context, docType string, input DocGenerationInput) (GeneratedDocInfo, error) {
	now := time.Now()
	ts := now.Format("20060102")
	seq := now.UnixMilli() % 100000
	if seq == 0 {
		// seq must never be 0: downstream uses it as the Proforma Invoice reference
		// (e.g. CI's pi_ref) and %05d would render a 0 as "00000".
		seq = 1
	}

	switch normalizeDocType(docType) {
	case tradeModels.DocTypeProformaInvoice:
		docNo := fmt.Sprintf("PI-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"buyer": %q,
	"seller": %q,
	"incoterms": %q,
	"payment_terms": %q,
	"total_amount": %.2f,
	"currency": %q,
	"valid_until": %q
}`, input.BuyerName, input.SellerName, input.Incoterms, input.PaymentTerms,
			input.TotalAmount, input.Currency, now.AddDate(0, 1, 0).Format("2006-01-02"))
		return GeneratedDocInfo{DocType: tradeModels.DocTypeProformaInvoice, DocNumber: docNo, Content: content}, nil

	case tradeModels.DocTypeCommercialInvoice:
		piRef := fmt.Sprintf("PI-%s-%05d", ts, seq)
		docNo := fmt.Sprintf("CI-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"pi_ref": %q,
	"quantity": 1,
	"amount": %.2f,
	"currency": %q,
	"vessel": "TBA",
	"pol": %q,
	"pod": "Destination Port"
}`, piRef, input.TotalAmount, input.Currency, input.Incoterms)
		return GeneratedDocInfo{DocType: tradeModels.DocTypeCommercialInvoice, DocNumber: docNo, Content: content}, nil

	case tradeModels.DocTypeSalesContract:
		docNo := fmt.Sprintf("SC-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"reference": "TRADE-%d",
	"buyer": %q,
	"seller": %q,
	"incoterms": %q,
	"payment_terms": %q,
	"amount": %.2f,
	"currency": %q,
	"validity_days": 30
}`, input.TradeID, input.BuyerName, input.SellerName, input.Incoterms, input.PaymentTerms,
			input.TotalAmount, input.Currency)
		return GeneratedDocInfo{DocType: tradeModels.DocTypeSalesContract, DocNumber: docNo, Content: content}, nil

	case tradeModels.DocTypePackingList:
		docNo := fmt.Sprintf("PL-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"reference": "TRADE-%d",
	"total_cartons": 1,
	"total_pallets": 1,
	"gross_weight_kg": 0,
	"net_weight_kg": 0,
	"volume_cbm": 0
}`, input.TradeID)
		return GeneratedDocInfo{DocType: tradeModels.DocTypePackingList, DocNumber: docNo, Content: content}, nil

	case tradeModels.DocTypeOriginCertificate:
		docNo := fmt.Sprintf("COO-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"origin": "China",
	"destination": "Buyer Country",
	"fta_type": "FORM E",
	"hs_code": "1704.90"
}`)
		return GeneratedDocInfo{DocType: tradeModels.DocTypeOriginCertificate, DocNumber: docNo, Content: content}, nil

	case tradeModels.DocTypeHealthCertificate:
		docNo := fmt.Sprintf("HC-REQ-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"product": "Candy Products",
	"producer": %q,
	"destination": "Buyer Country",
	"authority": "Local FDA"
}`, input.SellerName)
		return GeneratedDocInfo{DocType: tradeModels.DocTypeHealthCertificate, DocNumber: docNo, Content: content}, nil

	case "BILL_OF_LADING":
		docNo := fmt.Sprintf("BL-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"shipper": %q,
	"consignee": %q,
	"notify_party": %q,
	"vessel": "TBA",
	"port_of_loading": "Shanghai",
	"port_of_discharge": "Destination Port",
	"freight_terms": "PREPAID"
}`, input.SellerName, input.BuyerName, input.BuyerName)
		return GeneratedDocInfo{DocType: "BILL_OF_LADING", DocNumber: docNo, Content: content}, nil

	case "INGREDIENTS_DECLARATION":
		docNo := fmt.Sprintf("ING-%s-%05d", ts, seq)
		content := `{"product": "Candy Products", "ingredients": [], "allergens": [], "halal": false}`
		return GeneratedDocInfo{DocType: "INGREDIENTS_DECLARATION", DocNumber: docNo, Content: content}, nil

	case "SHIPPER_LETTER_OF_INSTRUCTION":
		docNo := fmt.Sprintf("SLI-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"shipper": %q,
	"consignee": %q,
	"origin_port": "Shanghai",
	"destination_port": "Destination Port",
	"cargo": "Candy Products",
	"fcl_status": true
}`, input.SellerName, input.BuyerName)
		return GeneratedDocInfo{DocType: "SHIPPER_LETTER_OF_INSTRUCTION", DocNumber: docNo, Content: content}, nil

	case "INSURANCE_CERTIFICATE":
		docNo := fmt.Sprintf("INS-%s-%05d", ts, seq)
		content := fmt.Sprintf(`{
	"insured": %q,
	"vessel": "TBA",
	"route": "Shanghai to Destination Port",
	"invoice_value": %.2f,
	"coverage": "110.0%%",
	"insured_amount": %.2f
}`, input.BuyerName, input.TotalAmount, input.TotalAmount*1.1)
		return GeneratedDocInfo{DocType: "INSURANCE_CERTIFICATE", DocNumber: docNo, Content: content}, nil

	default:
		return GeneratedDocInfo{}, fmt.Errorf("unsupported document type: %s", docType)
	}
}

func normalizeDocType(docType string) string {
	return strings.ToUpper(strings.TrimSpace(docType))
}
