#!/usr/bin/env python3
"""Generate data blocks for i18n_build_id_ms_offline.py"""
from pathlib import Path

OUT = Path(__file__).resolve().parent / "i18n_build_id_ms_offline.py"

# --- path overrides (from i18n_translate_id_ms.py) ---
OVERRIDES = r'''
_nav_id = {
    "dashboard": "Dasbor", "users": "Pengguna", "inquiries": "Permintaan Penawaran",
    "orders": "Pesanan", "returns": "Retur", "products": "Produk", "categories": "Kategori",
    "companies": "Perusahaan", "trades": "Perdagangan", "pricing": "Harga",
    "oemProjects": "Proyek OEM", "content": "Konten", "inventory": "Inventaris",
    "xlsx": "Alat XLSX", "shipments": "Pengiriman", "invoices": "Faktur",
    "management": "Manajemen", "superadmin": "Super Admin", "analytics": "Analitik",
    "financial": "Keuangan", "certifications": "Sertifikasi", "staff": "Staf",
    "auditLog": "Log Audit", "settings": "Pengaturan", "translations": "Terjemahan",
    "ai": "Aplikasi AI", "organizations": "Organisasi Pembeli", "channels": "Saluran",
    "webhooks": "Webhook", "hooks": "Hook & Acara", "coupons": "Kupon",
    "shipping_rates": "Pengiriman & Pajak", "tax_rates": "Tarif Pajak",
}
_nav_ms = {
    "dashboard": "Papan Pemuka", "users": "Pengguna", "inquiries": "Pertanyaan",
    "orders": "Pesanan", "returns": "Pemulangan", "products": "Produk", "categories": "Kategori",
    "companies": "Syarikat", "trades": "Perdagangan", "pricing": "Harga",
    "oemProjects": "Projek OEM", "content": "Kandungan", "inventory": "Inventori",
    "xlsx": "Alat XLSX", "shipments": "Penghantaran", "invoices": "Invois",
    "management": "Pengurusan", "superadmin": "Super Admin", "analytics": "Analitik",
    "financial": "Kewangan", "certifications": "Pensijilan", "staff": "Kakitangan",
    "auditLog": "Log Audit", "settings": "Tetapan", "translations": "Terjemahan",
    "ai": "Aplikasi AI", "organizations": "Organisasi Pembeli", "channels": "Saluran",
    "webhooks": "Webhook", "hooks": "Hook & Acara", "coupons": "Kupon",
    "shipping_rates": "Penghantaran & Cukai", "tax_rates": "Kadar Cukai",
}
for k, v in _nav_id.items():
    _add(f"admin.nav.{k}", v, _nav_ms[k])

_status_id = {"draft": "Draf", "sent": "Terkirim", "paid": "Lunas", "overdue": "Jatuh tempo",
              "cancelled": "Dibatalkan", "active": "Aktif", "inactive": "Nonaktif"}
_status_ms = {"draft": "Draf", "sent": "Dihantar", "paid": "Dibayar", "overdue": "Lewat tempoh",
              "cancelled": "Dibatalkan", "active": "Aktif", "inactive": "Tidak aktif"}
for k, v in _status_id.items():
    _add(f"admin.status_options.{k}", v, _status_ms[k])

_add("admin.langLabel", "ID", "MS")
_add("admin.langLabelShort", "ID", "MS")
_add("admin.langTitle", "Bahasa Indonesia", "Bahasa Melayu")
_add("admin.brand", "CandyPro Admin", "CandyPro Admin")
_add("admin.logout", "Keluar", "Log keluar")

_add("admin.dashboard.title", "Dasbor", "Papan Pemuka")
_add("admin.dashboard.subtitle", "Ikhtisar platform dan metrik utama sekilas.", "Gambaran platform dan metrik utama sepintas lalu.")
_add("admin.dashboard.loading", "Memuat statistik dasbor...", "Memuatkan statistik papan pemuka...")
_add("admin.dashboard.error", "Gagal memuat dasbor", "Ralat memuatkan papan pemuka")
_add("admin.dashboard.total_users", "Total Pengguna", "Jumlah Pengguna")
_add("admin.dashboard.total_orders", "Total Pesanan", "Jumlah Pesanan")
_add("admin.dashboard.total_inquiries", "Total Permintaan", "Jumlah Pertanyaan")
_add("admin.dashboard.total_revenue", "Total Pendapatan", "Jumlah Hasil")
_add("admin.dashboard.this_week", "minggu ini", "minggu ini")
_add("admin.dashboard.new_users_this_week", "{count} baru minggu ini", "{count} baharu minggu ini")
_add("admin.dashboard.pending", "menunggu", "menunggu")
_add("admin.dashboard.recent_activity", "Aktivitas Terbaru", "Aktiviti Terkini")
_add("admin.dashboard.col_activity", "Aktivitas", "Aktiviti")
_add("admin.dashboard.col_time", "Waktu", "Masa")
_add("admin.dashboard.no_activity", "Tidak ada aktivitas terbaru", "Tiada aktiviti terkini")
_add("admin.dashboard.revenue_this_month", "Pendapatan Bulan Ini", "Hasil Bulan Ini")
_add("admin.dashboard.active_customers", "Pelanggan Aktif", "Pelanggan Aktif")
_add("admin.dashboard.avg_order_value", "Nilai Pesanan Rata-rata", "Nilai Pesanan Purata")
_add("admin.dashboard.conversion_rate", "Tingkat Konversi", "Kadar Penukaran")
_add("admin.dashboard.revenue_chart", "Pendapatan (30 Hari)", "Hasil (30 Hari)")
_add("admin.dashboard.revenue", "Pendapatan", "Hasil")
_add("admin.dashboard.date", "Tanggal", "Tarikh")

for path, id_v, ms_v in [
    ("admin.products.title", "Produk", "Produk"),
    ("admin.inventory.title", "Inventaris", "Inventori"),
    ("admin.categories.title", "Kategori", "Kategori"),
    ("admin.coupons.title", "Kupon & Kartu Hadiah", "Kupon & Kad Hadiah"),
    ("admin.shippingRates.title", "Tarif Pengiriman", "Kadar Penghantaran"),
    ("admin.taxRates.title", "Tarif Pajak", "Kadar Cukai"),
    ("admin.shippingRates.description",
     "Tabel tarif pengiriman berdasarkan tujuan. Perkiraan hari hanya referensi penawaran — bukan jaminan waktu transit.",
     "Jadual kadar penghantaran mengikut destinasi. Anggaran hari adalah rujukan sebut harga — bukan jaminan masa transit."),
    ("admin.taxRates.description",
     "Tarif pajak negara/wilayah tujuan yang diterapkan saat checkout keranjang.",
     "Kadar cukai negara/wilayah destinasi yang digunakan semasa checkout troli."),
]:
    _add(path, id_v, ms_v)

for path, id_v, ms_v in [
    ("admin.products.ai_description_label", "Deskripsikan produk Anda", "Huraikan produk anda"),
    ("admin.products.ai_description_placeholder", "mis., cokelat susu 150g dengan almond, vegan, masa simpan 12 bulan, flow-wrap individual, 24 potong per display box, bersertifikat halal...", "cth., coklat susu 150g dengan badam, vegan, jumlah hayat 12 bulan, flow-wrap individu, 24 keping setiap kotak paparan, disahkan halal..."),
    ("admin.products.ai_empty_preview", "Masukkan deskripsi produk di kiri dan klik Generate untuk melihat field terisi AI di sini.", "Masukkan penerangan produk di sebelah kiri dan klik Jana untuk melihat medan diisi AI di sini."),
    ("admin.products.ai_generate_failed", "Generasi AI gagal. Coba deskripsi yang lebih detail.", "Penjanaan AI gagal. Cuba penerangan yang lebih terperinci."),
    ("admin.products.ai_section_dietary", "Label Diet", "Label Diet"),
    ("admin.products.ai_section_trade", "Perdagangan & Kemasan", "Perdagangan & Pembungkusan"),
    ("admin.products.ai_translate_reloaded", "Terjemahan selesai di server; memuat terjemahan terbaru dari database", "Terjemahan selesai di pelayan; memuatkan terjemahan terkini dari pangkalan data"),
    ("admin.products.alias", "Alias", "Alias"),
    ("admin.products.col_moq", "MOQ", "MOQ"),
    ("admin.products.col_status", "Status", "Status"),
    ("admin.products.cost_material", "Material", "Bahan"),
    ("admin.products.csv_hint", "Pisahkan dengan koma", "Pisahkan dengan koma"),
    ("admin.products.edit", "Edit", "Edit"),
    ("admin.products.field_cocoa_solids_pct", "Padatan Kakao %", "Kandungan Kakao %"),
    ("admin.products.field_gmo_status", "Status GMO", "Status GMO"),
    ("admin.products.field_gtin", "GTIN / Barcode", "GTIN / Barcode"),
    ("admin.products.field_hs_code", "Kode HS", "Kod HS"),
    ("admin.products.field_inner_pack_config", "Konfigurasi Kemasan Dalam", "Konfigurasi Pembungkusan Dalam"),
    ("admin.products.field_kosher", "Kosher", "Kosher"),
    ("admin.products.field_milk_solids_pct", "Padatan Susu %", "Kandungan Susu %"),
    ("admin.products.field_packs_per_carton", "Kemasan/Karton", "Pek/Karton"),
    ("admin.products.field_pallet_config", "Konfigurasi Palet", "Konfigurasi Palet"),
    ("admin.products.field_pieces_per_pack", "Potongan/Kemasan", "Keping/Pek"),
    ("admin.products.field_primary_packaging", "Kemasan Utama", "Pembungkusan Utama"),
    ("admin.products.field_protein_g", "Protein (g)", "Protein (g)"),
    ("admin.products.field_vegan", "Vegan", "Vegan"),
    ("admin.products.gmo_option_gmo", "GMO", "GMO"),
    ("admin.products.gmo_option_gmo_free_certified", "Bersertifikat Bebas GMO", "Disahkan Bebas GMO"),
    ("admin.products.gmo_option_non_gmo", "Non-GMO", "Non-GMO"),
    ("admin.products.halal", "Halal", "Halal"),
    ("admin.products.inner_pack_placeholder", "mis. 12 unit per display box", "cth. 12 unit setiap kotak paparan"),
    ("admin.products.label_template", "ID Template Label", "ID Templat Label"),
    ("admin.products.market_code", "Kode Pasar", "Kod Pasaran"),
    ("admin.products.market_saved", "Profil pasar disimpan.", "Profil pasaran disimpan."),
    ("admin.products.moq", "MOQ", "MOQ"),
    ("admin.products.oem", "OEM", "OEM"),
    ("admin.products.packaging_placeholder", "flow-wrap, foil, box, bag, jar", "flow-wrap, foil, box, bag, jar"),
    ("admin.products.pallet_config_placeholder", "mis. 48 kardus/lapisan × 5 lapisan", "cth. 48 kes/lapisan × 5 lapisan"),
    ("admin.products.section_dietary", "Label Diet", "Label Diet"),
    ("admin.products.section_market", "Profil Pasar", "Profil Pasaran"),
    ("admin.products.section_trade", "Perdagangan & Kemasan", "Perdagangan & Pembungkusan"),
    ("admin.products.slug", "Slug", "Slug"),
    ("admin.products.status", "Status", "Status"),
    ("admin.products.status_filter", "Status", "Status"),
    ("admin.products.thumbnail", "Thumbnail", "Imej Kenit"),
    ("admin.products.trans_name_placeholder", "Kosongkan untuk menggunakan nama default", "Biarkan kosong untuk menggunakan nama lalai"),
    ("admin.products.translations_hint", "Semua teks yang dihadapkan pelanggan hanya di sini. Bahasa Tionghoa adalah locale sumber; field skalar disinkronkan saat simpan.", "Semua teks berhadapan pelanggan hanya di sini. Bahasa Cina adalah locale sumber; medan skalar disegerakkan semasa simpan."),
    ("admin.inventory.batch_delete_confirm", "Yakin ingin menghapus {count} produk terpilih? Tindakan ini tidak dapat dibatalkan.", "Adakah anda pasti mahu memadam {count} produk terpilih? Tindakan ini tidak boleh dibuat asal."),
    ("admin.inventory.batch_delete_result", "{deleted} dihapus, {errors} kesalahan", "{deleted} dipadam, {errors} ralat"),
    ("admin.inventory.batch_edit_field", "Field", "Medan"),
    ("admin.inventory.batch_edit_field_halalCertified", "Bersertifikat Halal", "Disahkan Halal"),
    ("admin.inventory.batch_edit_field_hsCode", "Kode HS", "Kod HS"),
    ("admin.inventory.batch_edit_field_moq", "MOQ", "MOQ"),
    ("admin.inventory.batch_edit_field_status", "Status", "Status"),
    ("admin.inventory.batch_edit_selected_count", "Mengedit {count} produk", "Mengedit {count} produk"),
    ("admin.inventory.col_moq", "MOQ", "MOQ"),
    ("admin.inventory.col_sku", "SKU", "SKU"),
    ("admin.inventory.col_status", "Status", "Status"),
    ("admin.inventory.export_filename", "inventaris", "inventori"),
    ("admin.inventory.from_to", "{from} → {to}", "{from} → {to}"),
    ("admin.inventory.import_ai_mapping", "Pemetaan Saran AI", "Pemetaan Cadangan AI"),
    ("admin.inventory.import_drop_zone", "Klik atau seret file XLSX ke sini", "Klik atau seret fail XLSX ke sini"),
    ("admin.inventory.import_image_detected", "URL gambar terdeteksi — akan diunggah otomatis saat impor", "URL imej dikesan — akan dimuat naik automatik semasa import"),
    ("admin.inventory.import_preview_more", "... dan {n} baris lagi", "... dan {n} baris lagi"),
    ("admin.inventory.import_select_file", "Silakan pilih file XLSX", "Sila pilih fail XLSX"),
    ("admin.inventory.selected_count", "{count} dipilih", "{count} dipilih"),
    ("admin.inventory.transfer_no", "Transfer #", "Pemindahan #"),
    ("admin.inventory.type_add", "Tambah", "Tambah"),
    ("admin.categories.col_slug", "Slug", "Slug"),
    ("admin.categories.edit", "Edit", "Edit"),
    ("admin.categories.field_alias", "Alias", "Alias"),
    ("admin.categories.icon", "Ikon", "Ikon"),
    ("admin.categories.slug", "Slug", "Slug"),
    ("admin.categories.thumbnail", "URL Thumbnail", "URL Imej Kenit"),
    ("admin.coupons.col_status", "Status", "Status"),
    ("admin.coupons.showing", "{total} total", "{total} jumlah"),
    ("admin.shippingRates.col_days", "Hari", "Hari"),
    ("admin.shippingRates.col_status", "Status", "Status"),
    ("admin.shippingRates.edit", "Edit", "Edit"),
    ("admin.taxRates.col_status", "Status", "Status"),
    ("admin.taxRates.edit", "Edit", "Edit"),
    ("admin.taxRates.rate_hint", "Pecahan desimal, mis. 0.08875 = 8,875%", "Pecahan perpuluhan, cth. 0.08875 = 8.875%"),
    ("enum.inquiry_priority.normal", "Biasa", "Biasa"),
    ("enum.carrier.standard", "Standar", "Standard"),
    ("enum.tracking_provider.standard", "Standar", "Standard"),
]:
    _add(path, id_v, ms_v)
'''

# Shared word lexicon pairs (en, id, ms)
WORD_PAIRS = [
    ("Loading dashboard statistics...", "Memuat statistik dasbor...", "Memuatkan statistik papan pemuka..."),
    ("Error loading dashboard", "Gagal memuat dasbor", "Ralat memuatkan papan pemuka"),
    ("Manage product catalog with complete CRUD operations.", "Kelola katalog produk dengan operasi CRUD lengkap.", "Urus katalog produk dengan operasi CRUD penuh."),
    ("Track and manage product stock levels, values, and adjustments.", "Lacak dan kelola level stok, nilai, dan penyesuaian produk.", "Jejaki dan urus tahap stok, nilai, dan pelarasan produk."),
    ("Manage product categories with multilingual names, aliases, and descriptions.", "Kelola kategori produk dengan nama, alias, dan deskripsi multibahasa.", "Urus kategori produk dengan nama, alias, dan penerangan pelbagai bahasa."),
    ("Promotional codes and prepaid credits.", "Kode promosi dan kredit prabayar.", "Kod promosi dan kredit prabayar."),
    ("Destination country/region tax rates applied at cart checkout.", "Tarif pajak negara/wilayah tujuan yang diterapkan saat checkout keranjang.", "Kadar cukai negara/wilayah destinasi yang digunakan semasa checkout troli."),
    ("No shipping rates.", "Tidak ada tarif pengiriman.", "Tiada kadar penghantaran."),
    ("No tax rates configured.", "Tidak ada tarif pajak yang dikonfigurasi.", "Tiada kadar cukai dikonfigurasi."),
    ("No coupons.", "Tidak ada kupon.", "Tiada kupon."),
    ("No gift cards.", "Tidak ada kartu hadiah.", "Tiada kad hadiah."),
    ("No products found.", "Tidak ada produk ditemukan.", "Tiada produk dijumpai."),
    ("No categories found", "Tidak ada kategori ditemukan", "Tiada kategori dijumpai"),
    ("No inventory data found.", "Tidak ada data inventaris ditemukan.", "Tiada data inventori dijumpai."),
    ("Loading products...", "Memuat produk...", "Memuatkan produk..."),
    ("Loading inventory...", "Memuat inventaris...", "Memuatkan inventori..."),
    ("Loading...", "Memuat...", "Memuatkan..."),
    ("Add Product", "Tambah Produk", "Tambah Produk"),
    ("Add Category", "Tambah Kategori", "Tambah Kategori"),
    ("Add Rate", "Tambah Tarif", "Tambah Kadar"),
    ("Add Tax Rate", "Tambah Tarif Pajak", "Tambah Kadar Cukai"),
    ("Create Coupon", "Buat Kupon", "Cipta Kupon"),
    ("Create Gift Card", "Buat Kartu Hadiah", "Cipta Kad Hadiah"),
    ("Create Product", "Buat Produk", "Cipta Produk"),
    ("Edit Product", "Edit Produk", "Edit Produk"),
    ("Edit Category", "Edit Kategori", "Edit Kategori"),
    ("Delete this product?", "Hapus produk ini?", "Padam produk ini?"),
    ("Delete this category?", "Hapus kategori ini?", "Padam kategori ini?"),
    ("Product name is required.", "Nama produk wajib diisi.", "Nama produk diperlukan."),
    ("Product created successfully.", "Produk berhasil dibuat.", "Produk berjaya dicipta."),
    ("Product updated successfully.", "Produk berhasil diperbarui.", "Produk berjaya dikemas kini."),
    ("Product deleted successfully.", "Produk berhasil dihapus.", "Produk berjaya dipadam."),
    ("Showing {from} to {to} of {total}", "Menampilkan {from} hingga {to} dari {total}", "Menunjukkan {from} hingga {to} daripada {total}"),
    ("Previous", "Sebelumnya", "Sebelum"),
    ("Next", "Berikutnya", "Seterusnya"),
    ("Search", "Cari", "Cari"),
    ("Search by product name or SKU...", "Cari berdasarkan nama produk atau SKU...", "Cari mengikut nama produk atau SKU..."),
    ("Status", "Status", "Status"),
    ("Save", "Simpan", "Simpan"),
    ("Cancel", "Batal", "Batal"),
    ("Edit", "Edit", "Edit"),
    ("Delete", "Hapus", "Padam"),
    ("Create", "Buat", "Cipta"),
    ("Update", "Perbarui", "Kemas kini"),
    ("Actions", "Tindakan", "Tindakan"),
    ("Name", "Nama", "Nama"),
    ("Description", "Deskripsi", "Penerangan"),
    ("Category", "Kategori", "Kategori"),
    ("Stock", "Stok", "Stok"),
    ("Active", "Aktif", "Aktif"),
    ("Inactive", "Nonaktif", "Tidak aktif"),
    ("Draft", "Draf", "Draf"),
    ("Pending", "Menunggu", "Menunggu"),
    ("Confirmed", "Dikonfirmasi", "Disahkan"),
    ("Cancelled", "Dibatalkan", "Dibatalkan"),
    ("Paid", "Lunas", "Dibayar"),
    ("Unpaid", "Belum dibayar", "Belum dibayar"),
    ("Coupons", "Kupon", "Kupon"),
    ("Gift Cards", "Kartu Hadiah", "Kad Hadiah"),
    ("Shipping Rates", "Tarif Pengiriman", "Kadar Penghantaran"),
    ("Tax Rates", "Tarif Pajak", "Kadar Cukai"),
    ("Destination", "Tujuan", "Destinasi"),
    ("Carrier", "Kurir", "Penghantar"),
    ("Country", "Negara", "Negara"),
    ("Region", "Wilayah", "Wilayah"),
    ("Region / State", "Wilayah / Provinsi", "Wilayah / Negeri"),
    ("Rate", "Tarif", "Kadar"),
    ("Currency", "Mata Uang", "Mata Wang"),
    ("Code", "Kode", "Kod"),
    ("Type", "Tipe", "Jenis"),
    ("Value", "Nilai", "Nilai"),
    ("Balance", "Saldo", "Baki"),
    ("Percentage", "Persentase", "Peratus"),
    ("Fixed Amount", "Jumlah Tetap", "Jumlah Tetap"),
    ("Min Order", "Pesanan Minimum", "Pesanan Minimum"),
    ("Starts At", "Mulai", "Bermula"),
    ("Expires At", "Berakhir", "Tamat"),
    ("Used", "Digunakan", "Digunakan"),
    ("Initial", "Awal", "Permulaan"),
    ("Adjust Stock", "Sesuaikan Stok", "Laraskan Stok"),
    ("Current Stock", "Stok Saat Ini", "Stok Semasa"),
    ("New Stock", "Stok Baru", "Stok Baharu"),
    ("Low Stock", "Stok Rendah", "Stok Rendah"),
    ("Out of Stock", "Stok Habis", "Stok Habis"),
    ("In Stock", "Tersedia", "Dalam Stok"),
    ("Total Products", "Total Produk", "Jumlah Produk"),
    ("Total Value", "Total Nilai", "Jumlah Nilai"),
    ("Export", "Ekspor", "Eksport"),
    ("Import XLSX", "Impor XLSX", "Import XLSX"),
    ("Select All", "Pilih Semua", "Pilih Semua"),
    ("No data available", "Tidak ada data", "Tiada data"),
    ("Failed to load categories", "Gagal memuat kategori", "Gagal memuatkan kategori"),
    ("Save failed", "Gagal menyimpan", "Gagal menyimpan"),
    ("Category created", "Kategori dibuat", "Kategori dicipta"),
    ("Category updated", "Kategori diperbarui", "Kategori dikemas kini"),
    ("Category deleted", "Kategori dihapus", "Kategori dipadam"),
    ("Slug is required", "Slug wajib diisi", "Slug diperlukan"),
    ("Chinese category name is required", "Nama kategori bahasa Tionghoa wajib diisi", "Nama kategori bahasa Cina diperlukan"),
    ("Skip to main content", "Lewati ke konten utama", "Langkau ke kandungan utama"),
    ("Close", "Tutup", "Tutup"),
    ("Loading…", "Memuat…", "Memuatkan…"),
    ("Page Not Found", "Halaman Tidak Ditemukan", "Halaman Tidak Dijumpai"),
    ("Access Denied", "Akses Ditolak", "Akses Ditolak"),
    ("Server Error", "Kesalahan Server", "Ralat Pelayan"),
    ("Try Again", "Coba Lagi", "Cuba Lagi"),
    ("Go to Home", "Ke Beranda", "Ke Laman Utama"),
    ("Customer", "Pelanggan", "Pelanggan"),
    ("Admin", "Admin", "Admin"),
    ("Super Admin", "Super Admin", "Super Admin"),
    ("Yes", "Ya", "Ya"),
    ("No", "Tidak", "Tidak"),
    ("Required", "Wajib", "Diperlukan"),
    ("Invalid email format", "Format email tidak valid", "Format e-mel tidak sah"),
    ("Could not save. Please try again.", "Tidak dapat menyimpan. Silakan coba lagi.", "Tidak dapat menyimpan. Sila cuba lagi."),
    ("Something went wrong. Please try again.", "Terjadi kesalahan. Silakan coba lagi.", "Sesuatu tidak kena. Sila cuba lagi."),
    ("Accept All", "Terima Semua", "Terima Semua"),
    ("Essential Only", "Esensial Saja", "Asas Sahaja"),
    ("Cookie Preferences", "Preferensi Cookie", "Keutamaan Kuki"),
    ("Bahasa Indonesia", "Bahasa Indonesia", "Bahasa Indonesia"),
    ("Bahasa Melayu", "Bahasa Melayu", "Bahasa Melayu"),
    ("English", "Bahasa Inggris", "Bahasa Inggeris"),
    ("Chinese", "Bahasa Tionghoa", "Bahasa Cina"),
    ("Traditional Chinese", "Bahasa Tionghoa Tradisional", "Bahasa Cina Tradisional"),
    ("Japanese", "Bahasa Jepang", "Bahasa Jepun"),
    ("Korean", "Bahasa Korea", "Bahasa Korea"),
    ("Arabic", "Bahasa Arab", "Bahasa Arab"),
    ("Thai", "Bahasa Thailand", "Bahasa Thai"),
    ("Vietnamese", "Bahasa Vietnam", "Bahasa Vietnam"),
    ("Indonesian", "Bahasa Indonesia", "Bahasa Indonesia"),
    ("Malay", "Bahasa Melayu", "Bahasa Melayu"),
]

# Word-level lexicon
WORDS = [
    ("Loading", "Memuat", "Memuatkan"),
    ("Error loading", "Gagal memuat", "Ralat memuatkan"),
    ("Failed to load", "Gagal memuat", "Gagal memuatkan"),
    ("Failed to", "Gagal", "Gagal"),
    ("No ", "Tidak ada ", "Tiada "),
    (" not ", " tidak ", " tidak "),
    (" found", " ditemukan", " dijumpai"),
    ("Add ", "Tambah ", "Tambah "),
    ("Create ", "Buat ", "Cipta "),
    ("Edit ", "Edit ", "Edit "),
    ("Delete ", "Hapus ", "Padam "),
    ("Update ", "Perbarui ", "Kemas kini "),
    ("Search", "Cari", "Cari"),
    ("Filter", "Filter", "Tapis"),
    ("Export", "Ekspor", "Eksport"),
    ("Import", "Impor", "Import"),
    ("Save", "Simpan", "Simpan"),
    ("Cancel", "Batal", "Batal"),
    ("Confirm", "Konfirmasi", "Sahkan"),
    ("Actions", "Tindakan", "Tindakan"),
    ("Status", "Status", "Status"),
    ("Name", "Nama", "Nama"),
    ("Description", "Deskripsi", "Penerangan"),
    ("Title", "Judul", "Tajuk"),
    ("Products", "Produk", "Produk"),
    ("Product", "Produk", "Produk"),
    ("Categories", "Kategori", "Kategori"),
    ("Category", "Kategori", "Kategori"),
    ("Inventory", "Inventaris", "Inventori"),
    ("Orders", "Pesanan", "Pesanan"),
    ("Order", "Pesanan", "Pesanan"),
    ("Users", "Pengguna", "Pengguna"),
    ("User", "Pengguna", "Pengguna"),
    ("Customers", "Pelanggan", "Pelanggan"),
    ("Customer", "Pelanggan", "Pelanggan"),
    ("Revenue", "Pendapatan", "Hasil"),
    ("Dashboard", "Dasbor", "Papan Pemuka"),
    ("Settings", "Pengaturan", "Tetapan"),
    ("Analytics", "Analitik", "Analitik"),
    ("Financial", "Keuangan", "Kewangan"),
    ("Management", "Manajemen", "Pengurusan"),
    ("Content", "Konten", "Kandungan"),
    ("Shipments", "Pengiriman", "Penghantaran"),
    ("Invoices", "Faktur", "Invois"),
    ("Invoice", "Faktur", "Invois"),
    ("Coupons", "Kupon", "Kupon"),
    ("Coupon", "Kupon", "Kupon"),
    ("Pricing", "Harga", "Harga"),
    ("Companies", "Perusahaan", "Syarikat"),
    ("Company", "Perusahaan", "Syarikat"),
    ("Staff", "Staf", "Kakitangan"),
    ("Warehouse", "Gudang", "Gudang"),
    ("Warehouses", "Gudang", "Gudang"),
    ("Stock", "Stok", "Stok"),
    ("Quantity", "Jumlah", "Kuantiti"),
    ("Amount", "Jumlah", "Jumlah"),
    ("Total", "Total", "Jumlah"),
    ("Active", "Aktif", "Aktif"),
    ("Inactive", "Nonaktif", "Tidak aktif"),
    ("Pending", "Menunggu", "Menunggu"),
    ("Confirmed", "Dikonfirmasi", "Disahkan"),
    ("Cancelled", "Dibatalkan", "Dibatalkan"),
    ("Processing", "Diproses", "Diproses"),
    ("Completed", "Selesai", "Selesai"),
    ("Delivered", "Diterima", "Diterima"),
    ("Shipped", "Dikirim", "Dihantar"),
    ("Production", "Produksi", "Pengeluaran"),
    ("Approved", "Disetujui", "Diluluskan"),
    ("Rejected", "Ditolak", "Ditolak"),
    ("Verified", "Terverifikasi", "Disahkan"),
    ("Suspended", "Ditangguhkan", "Digantung"),
    ("Deleted", "Dihapus", "Dipadam"),
    ("Unknown", "Tidak diketahui", "Tidak diketahui"),
    ("Success", "Berhasil", "Berjaya"),
    ("Error", "Kesalahan", "Ralat"),
    ("Failed", "Gagal", "Gagal"),
    ("Running", "Berjalan", "Sedang berjalan"),
    ("Warnings", "Peringatan", "Amaran"),
    ("Passed", "Lulus", "Lulus"),
    ("Previous", "Sebelumnya", "Sebelum"),
    ("Next", "Berikutnya", "Seterusnya"),
    ("Showing", "Menampilkan", "Menunjukkan"),
    ("Date", "Tanggal", "Tarikh"),
    ("Time", "Waktu", "Masa"),
    ("Email", "Email", "E-mel"),
    ("Phone", "Telepon", "Telefon"),
    ("Password", "Kata Sandi", "Kata Laluan"),
    ("Address", "Alamat", "Alamat"),
    ("Country", "Negara", "Negara"),
    ("Region", "Wilayah", "Wilayah"),
    ("Notes", "Catatan", "Nota"),
    ("Reason", "Alasan", "Sebab"),
    ("Type", "Tipe", "Jenis"),
    ("Value", "Nilai", "Nilai"),
    ("Rate", "Tarif", "Kadar"),
    ("Currency", "Mata Uang", "Mata Wang"),
    ("Destination", "Tujuan", "Destinasi"),
    ("Carrier", "Kurir", "Penghantar"),
    ("Weight", "Berat", "Berat"),
    ("Cost", "Biaya", "Kos"),
    ("Profit", "Laba", "Keuntungan"),
    ("Report", "Laporan", "Laporan"),
    ("Reports", "Laporan", "Laporan"),
    ("Activity", "Aktivitas", "Aktiviti"),
    ("History", "Riwayat", "Sejarah"),
    ("Details", "Detail", "Butiran"),
    ("Summary", "Ringkasan", "Ringkasan"),
    ("Thumbnail", "Thumbnail", "Imej Kenit"),
    ("Upload", "Unggah", "Muat naik"),
    ("Download", "Unduh", "Muat turun"),
    ("Translate", "Terjemahkan", "Terjemah"),
    ("Translating", "Menerjemahkan", "Menterjemah"),
    ("Generating", "Menghasilkan", "Menjana"),
    ("Saving", "Menyimpan", "Menyimpan"),
    ("Deleting", "Menghapus", "Memadam"),
    ("Applying", "Menerapkan", "Menggunakan"),
    ("Parsing", "Mengurai", "Menghuraikan"),
    ("Importing", "Mengimpor", "Mengimport"),
    ("Exporting", "Mengekspor", "Mengeksport"),
    ("Select", "Pilih", "Pilih"),
    ("Selected", "Dipilih", "Dipilih"),
    ("Clear", "Hapus", "Kosongkan"),
    ("Reload", "Muat Ulang", "Muat semula"),
    ("Optional", "Opsional", "Pilihan"),
    ("Required", "Wajib", "Diperlukan"),
    ("Invalid", "Tidak valid", "Tidak sah"),
    ("Available", "Tersedia", "Tersedia"),
    ("Featured", "Unggulan", "Pilihan"),
    ("Published", "Dipublikasikan", "Diterbitkan"),
    ("Draft", "Draf", "Draf"),
    ("Open", "Terbuka", "Terbuka"),
    ("Closed", "Ditutup", "Ditutup"),
    ("Overdue", "Jatuh tempo", "Lewat tempoh"),
    ("Expired", "Kedaluwarsa", "Tamat tempoh"),
    ("Partial", "Sebagian", "Separa"),
    ("Refunded", "Dikembalikan", "Dibayar balik"),
    ("Returned", "Dikembalikan", "Dipulangkan"),
    ("Contacted", "Dihubungi", "Dihubungi"),
    ("Negotiating", "Negosiasi", "Rundingan"),
    ("Quoted", "Dikutip", "Sebut harga"),
    ("Converted", "Dikonversi", "Ditukar"),
    ("Won", "Menang", "Menang"),
    ("Lost", "Kalah", "Kalah"),
    ("Normal", "Normal", "Biasa"),
    ("High", "Tinggi", "Tinggi"),
    ("Low", "Rendah", "Rendah"),
    ("Urgent", "Mendesak", "Segera"),
    ("Standard", "Standar", "Standard"),
    ("Exception", "Pengecualian", "Pengecualian"),
    ("Contract", "Kontrak", "Kontrak"),
    ("Quotation", "Penawaran", "Sebut harga"),
    ("Delivery", "Pengiriman", "Penghantaran"),
    ("Sampling", "Sampel", "Sampel"),
    ("Formulation", "Formulasi", "Formulasi"),
    ("Inquiry", "Permintaan", "Pertanyaan"),
    ("Inquiries", "Permintaan", "Pertanyaan"),
    ("Returns", "Retur", "Pemulangan"),
    ("Channels", "Saluran", "Saluran"),
    ("Organizations", "Organisasi", "Organisasi"),
    ("Translations", "Terjemahan", "Terjemahan"),
    ("Certifications", "Sertifikasi", "Pensijilan"),
    ("Audit Log", "Log Audit", "Log Audit"),
    ("Hooks & Events", "Hook & Acara", "Hook & Acara"),
    ("Shipping & Tax", "Pengiriman & Pajak", "Penghantaran & Cukai"),
    ("Sea Freight", "Pengiriman Laut", "Penghantaran Laut"),
    ("Air Freight", "Pengiriman Udara", "Penghantaran Udara"),
    ("In transit", "Dalam transit", "Dalam transit"),
    ("In progress", "Sedang berlangsung", "Sedang dijalankan"),
    ("Out for delivery", "Dalam pengiriman", "Dalam penghantaran"),
    ("Customs cleared", "Bea cukai selesai", "Kastam selesai"),
    ("Arrived at port", "Tiba di pelabuhan", "Tiba di pelabuhan"),
    ("Picked up", "Diambil kurir", "Diambil"),
    ("Dispatched", "Telah dikirim", "Dihantar"),
    ("Commercial Invoice", "Faktur Komersial", "Invois Komersial"),
    ("Proforma Invoice", "Faktur Proforma", "Invois Proforma"),
    ("Packing List", "Daftar Kemasan", "Senarai Pembungkusan"),
    ("Bill of Lading", "Bill of Lading", "Bill of Lading"),
    ("Sales Contract", "Kontrak Penjualan", "Kontrak Jualan"),
    ("Credit Note", "Nota Kredit", "Nota Kredit"),
    ("Health Certificate", "Sertifikat Kesehatan", "Sijil Kesihatan"),
    ("Origin Certificate", "Sertifikat Asal", "Sijil Asal-usul"),
    ("please try again", "silakan coba lagi", "sila cuba lagi"),
    ("Please try again", "Silakan coba lagi", "Sila cuba lagi"),
    ("Could not", "Tidak dapat", "Tidak dapat"),
    ("is required", "wajib diisi", "diperlukan"),
    ("must be at least", "minimal", "mestilah sekurang-kurangnya"),
    ("characters", "karakter", "aksara"),
    ("An error occurred", "Terjadi kesalahan", "Ralat berlaku"),
    ("Something went wrong", "Terjadi kesalahan", "Sesuatu tidak kena"),
    ("Back to Home", "Kembali ke Beranda", "Kembali ke Laman Utama"),
    ("Refresh Page", "Muat Ulang Halaman", "Muat Semula Halaman"),
    ("Page {current} of {total}", "Halaman {current} dari {total}", "Halaman {current} daripada {total}"),
    ("Pagination", "Paginasi", "Penomboran"),
    ("Contact us on WhatsApp", "Hubungi kami via WhatsApp", "Hubungi kami melalui WhatsApp"),
    ("WhatsApp Us", "WhatsApp Kami", "WhatsApp Kami"),
    ("Cookie Policy", "Kebijakan Cookie", "Dasar Kuki"),
    ("Learn more about our", "Pelajari lebih lanjut tentang", "Ketahui lebih lanjut tentang"),
    ("Breadcrumb", "Breadcrumb", "Breadcrumb"),
    ("Language", "Bahasa", "Bahasa"),
    ("Switch to dark mode", "Beralih ke mode gelap", "Tukar ke mod gelap"),
    ("Switch to light mode", "Beralih ke mode terang", "Tukar ke mod cerah"),
    ("Toggle menu", "Buka/tutup menu", "Togol menu"),
    ("Close menu", "Tutup menu", "Tutup menu"),
    ("Scroll to top", "Gulir ke atas", "Tatal ke atas"),
    ("Write something…", "Tulis sesuatu…", "Tulis sesuatu…"),
    ("Bold", "Tebal", "Tebal"),
    ("Italic", "Miring", "Condong"),
    ("Underline", "Garis bawah", "Garis bawah"),
    ("Paragraph", "Paragraf", "Perenggan"),
    ("Bullet List", "Daftar Bullet", "Senarai Bullet"),
    ("Ordered List", "Daftar Berurutan", "Senarai Berangka"),
    ("Blockquote", "Blockquote", "Blockquote"),
    ("Align Left", "Rata Kiri", "Jajar Kiri"),
    ("Align Center", "Rata Tengah", "Jajar Tengah"),
    ("Align Right", "Rata Kanan", "Jajar Kanan"),
    ("Insert Link", "Sisipkan Tautan", "Masukkan Pautan"),
    ("Insert Image", "Sisipkan Gambar", "Masukkan Imej"),
    ("Undo", "Urungkan", "Buat asal"),
    ("Redo", "Ulangi", "Buat semula"),
    ("Remove", "Hapus", "Buang"),
    ("Set", "Atur", "Tetapkan"),
    ("Uploading image…", "Mengunggah gambar…", "Memuat naik imej…"),
    ("Text formatting", "Format teks", "Format teks"),
    ("Heading 1", "Heading 1", "Tajuk 1"),
    ("Heading 2", "Heading 2", "Tajuk 2"),
    ("Heading 3", "Heading 3", "Tajuk 3"),
    ("Link URL", "URL Tautan", "URL Pautan"),
    ("Strikethrough", "Coret", "Garis lorek"),
    ("MOQ: ", "MOQ: ", "MOQ: "),
    ("Valid until {date}", "Berlaku hingga {date}", "Sah sehingga {date}"),
    ("Factory", "Pabrik", "Kilang"),
    ("Production line", "Lini produksi", "Barisan pengeluaran"),
    ("Quality control", "Kontrol kualitas", "Kawalan kualiti"),
    ("Packaging area", "Area pengemasan", "Kawasan pembungkusan"),
    ("Quality Laboratory", "Laboratorium Kualitas", "Makmal Kualiti"),
    ("Our Factory", "Pabrik Kami", "Kilang Kami"),
    ("Image column", "Kolom gambar", "Lajur imej"),
    ("B2B Candy Manufacturing", "Manufaktur Permen B2B", "Pembuatan Gula-gula B2B"),
    ("Clear input", "Hapus input", "Kosongkan input"),
    ("Please check your internet connection and try again.", "Periksa koneksi internet Anda dan coba lagi.", "Sila semak sambungan internet anda dan cuba lagi."),
    ("This site works best with JavaScript enabled. Use the links below to continue browsing.", "Situs ini bekerja optimal dengan JavaScript aktif. Gunakan tautan di bawah untuk melanjutkan.", "Laman ini berfungsi optimum dengan JavaScript diaktifkan. Gunakan pautan di bawah untuk meneruskan."),
    ("Sorry, the page you are looking for doesn't exist.", "Maaf, halaman yang Anda cari tidak ada.", "Maaf, halaman yang anda cari tidak wujud."),
    ("Something went wrong on our end. Please try again later.", "Terjadi kesalahan di sisi kami. Silakan coba lagi nanti.", "Sesuatu tidak kena di pihak kami. Sila cuba lagi nanti."),
    ("You do not have permission to access this page.", "Anda tidak memiliki izin untuk mengakses halaman ini.", "Anda tidak mempunyai kebenaran untuk mengakses halaman ini."),
    ("You do not have permission to access this resource.", "Anda tidak memiliki izin untuk mengakses sumber daya ini.", "Anda tidak mempunyai kebenaran untuk mengakses sumber ini."),
    ("Invalid format", "Format tidak valid", "Format tidak sah"),
    ("Invalid input", "Input tidak valid", "Input tidak sah"),
    ("Company Name", "Nama Perusahaan", "Nama Syarikat"),
    ("Contact Person", "Kontak Person", "Orang Hubungan"),
    ("{field} is required", "{field} wajib diisi", "{field} diperlukan"),
    ("Must be at least {min} characters", "Minimal {min} karakter", "Sekurang-kurangnya {min} aksara"),
    ("Invalid phone format", "Format telepon tidak valid", "Format telefon tidak sah"),
    ("global", "global", "global"),
    ("Partially shipped", "Sebagian dikirim", "Sebahagian dihantar"),
    ("Partially delivered", "Sebagian diterima", "Sebahagian diterima"),
    ("Partially returned", "Sebagian dikembalikan", "Sebahagian dipulangkan"),
    ("Pending confirmation", "Menunggu konfirmasi", "Menunggu pengesahan"),
    ("Pending approval", "Menunggu persetujuan", "Menunggu kelulusan"),
    ("Post", "Artikel", "Artikel"),
    ("Case", "Studi Kasus", "Kajian Kes"),
    ("Accepted", "Diterima", "Diterima"),
    ("Requested", "Diminta", "Diminta"),
    ("Received", "Diterima", "Diterima"),
    ("Sent", "Terkirim", "Dihantar"),
    ("Voided", "Dibatalkan", "Dibatalkan"),
    ("Updated", "Diperbarui", "Dikemas kini"),
    ("Created", "Dibuat", "Dicipta"),
    ("Apply", "Terapkan", "Gunakan"),
    ("Apply Changes", "Terapkan Perubahan", "Gunakan Perubahan"),
    ("Batch Edit", "Edit Massal", "Edit Pukal"),
    ("Batch Delete", "Hapus Massal", "Padam Pukal"),
    ("Confirm Batch Delete", "Konfirmasi Hapus Massal", "Sahkan Padam Pukal"),
    ("Base Price", "Harga Dasar", "Harga Asas"),
    ("Lead Time", "Waktu Tunggu", "Masa Tunggu"),
    ("Shelf Life", "Masa Simpan", "Jumlah Hayat"),
    ("Storage", "Penyimpanan", "Penyimpanan"),
    ("Ingredients", "Bahan", "Bahan"),
    ("Allergens", "Alergen", "Alergen"),
    ("Certifications", "Sertifikasi", "Pensijilan"),
    ("Flavors", "Rasa", "Perisa"),
    ("Shapes", "Bentuk", "Bentuk"),
    ("Images", "Gambar", "Imej"),
    ("Halal", "Halal", "Halal"),
    ("Organic", "Organik", "Organik"),
    ("Vegan", "Vegan", "Vegan"),
    ("Kosher", "Kosher", "Kosher"),
    ("Gluten-Free", "Bebas Gluten", "Bebas Gluten"),
    ("Sugar-Free", "Bebas Gula", "Bebas Gula"),
    ("Nutrition", "Nutrisi", "Pemakanan"),
    ("Compliance", "Kepatuhan", "Pematuhan"),
    ("Logistics", "Logistik", "Logistik"),
    ("Material", "Material", "Bahan"),
    ("Labor", "Tenaga Kerja", "Buruh"),
    ("Dimensions", "Dimensi", "Dimensi"),
    ("Length", "Panjang", "Panjang"),
    ("Width", "Lebar", "Lebar"),
    ("Height", "Tinggi", "Tinggi"),
    ("Protein", "Protein", "Protein"),
    ("Fat", "Lemak", "Lemak"),
    ("Fiber", "Serat", "Serat"),
    ("Salt", "Garam", "Garam"),
    ("Sugars", "Gula", "Gula"),
    ("Carbohydrates", "Karbohidrat", "Karbohidrat"),
    ("Energy", "Energi", "Tenaga"),
    ("Additives", "Aditif", "Aditif"),
    ("Sweetener Type", "Jenis Pemanis", "Jenis Pemanis"),
    ("May Contain", "Mungkin Mengandung", "Mungkin Mengandungi"),
    ("Sample", "Sampel", "Sampel"),
    ("Transfer", "Transfer", "Pemindahan"),
    ("Transfers", "Transfer", "Pemindahan"),
    ("From Warehouse", "Dari Gudang", "Dari Gudang"),
    ("To Warehouse", "Ke Gudang", "Ke Gudang"),
    ("Restock", "Restok", "Stok semula"),
    ("Correction", "Koreksi", "Pembetulan"),
    ("Damage/Loss", "Kerusakan/Kehilangan", "Kerosakan/Kehilangan"),
    ("Customer Return", "Retur Pelanggan", "Pemulangan Pelanggan"),
    ("Inventory Audit", "Audit Inventaris", "Audit Inventori"),
    ("Other", "Lainnya", "Lain-lain"),
    ("Set To", "Atur Ke", "Tetapkan Kepada"),
    ("Subtract", "Kurangi", "Tolak"),
    ("Adjustment Type", "Jenis Penyesuaian", "Jenis Pelarasan"),
    ("Unit Value", "Nilai Satuan", "Nilai Unit"),
    ("Min Weight", "Berat Minimum", "Berat Minimum"),
    ("Max Weight", "Berat Maksimum", "Berat Maksimum"),
    ("Base Cost", "Biaya Dasar", "Kos Asas"),
    ("Cost per kg", "Biaya per kg", "Kos per kg"),
    ("Est. Days", "Perkiraan Hari", "Anggaran Hari"),
    ("Min Order", "Pesanan Min.", "Pesanan Min."),
    ("Fixed Amount", "Jumlah Tetap", "Jumlah Tetap"),
    ("Percentage", "Persentase", "Peratus"),
    ("All Categories", "Semua Kategori", "Semua Kategori"),
    ("All statuses", "Semua status", "Semua status"),
    ("All Stock", "Semua Stok", "Semua Stok"),
    ("Filter by category", "Filter berdasarkan kategori", "Tapis mengikut kategori"),
    ("Filter by stock status", "Filter berdasarkan status stok", "Tapis mengikut status stok"),
    ("Clear filters", "Hapus filter", "Kosongkan tapisan"),
    ("Translate missing locales", "Terjemahkan locale yang hilang", "Terjemah locale yang tiada"),
    ("AI Translate All", "Terjemahkan Semua dengan AI", "Terjemah Semua dengan AI"),
    ("Generate with AI", "Hasilkan dengan AI", "Jana dengan AI"),
    ("Save Product", "Simpan Produk", "Simpan Produk"),
    ("Basic Information", "Informasi Dasar", "Maklumat Asas"),
    ("Column Mapping", "Pemetaan Kolom", "Pemetaan Lajur"),
    ("Download Template", "Unduh Template", "Muat Turun Templat"),
    ("Apply Import", "Terapkan Impor", "Gunakan Import"),
    ("Preview Import Data", "Pratinjau Data Impor", "Pratonton Data Import"),
    ("Import complete: {created} created, {updated} updated, {errors} errors",
     "Impor selesai: {created} dibuat, {updated} diperbarui, {errors} kesalahan",
     "Import selesai: {created} dicipta, {updated} dikemas kini, {errors} ralat"),
    ("Updated {updated}, {errors} errors", "Diperbarui {updated}, {errors} kesalahan", "Dikemas kini {updated}, {errors} ralat"),
    ("{count} selected", "{count} dipilih", "{count} dipilih"),
    ("{total} total", "{total} total", "{total} jumlah"),
    ("{from} → {to}", "{from} → {to}", "{from} → {to}"),
    ("Editing {count} products", "Mengedit {count} produk", "Mengedit {count} produk"),
    ("Are you sure you want to delete {count} selected products? This action cannot be undone.",
     "Yakin ingin menghapus {count} produk terpilih? Tindakan ini tidak dapat dibatalkan.",
     "Adakah anda pasti mahu memadam {count} produk terpilih? Tindakan ini tidak boleh dibatalkan."),
    ("Decimal fraction, e.g. 0.08875 = 8.875%", "Pecahan desimal, mis. 0.08875 = 8,875%", "Pecahan perpuluhan, cth. 0.08875 = 8.875%"),
    ("Reference transit estimate for internal quoting. Subject to change; confirm at order time.",
     "Perkiraan transit referensi untuk penawaran internal. Dapat berubah; konfirmasi saat pemesanan.",
     "Anggaran transit rujukan untuk sebut harga dalaman. Boleh berubah; sahkan semasa pesanan."),
    ("Country (ISO)", "Negara (ISO)", "Negara (ISO)"),
    ("Base Price (USD)", "Harga Dasar (USD)", "Harga Asas (USD)"),
    ("OG Image (Social Share)", "Gambar OG (Berbagi Sosial)", "Imej OG (Kongsi Sosial)"),
    ("Optional. Overrides thumbnail for Facebook/LinkedIn previews. 1200×630 recommended.",
     "Opsional. Mengganti thumbnail untuk pratinjau Facebook/LinkedIn. Disarankan 1200×630.",
     "Pilihan. Menggantikan imej kenit untuk pratonton Facebook/LinkedIn. Disyorkan 1200×630."),
    ("Enter after sales verification for catalog display. You may state a specific reference (e.g. \"25 business days after order confirmation\") — do not use vague promises like \"approx. X weeks\". Leave blank or use \"confirmed at order time\" until verified.",
     "Masukkan setelah verifikasi penjualan untuk tampilan katalog. Anda dapat menyatakan referensi spesifik (mis. \"25 hari kerja setelah konfirmasi pesanan\") — jangan gunakan janji vague seperti \"sekitar X minggu\". Kosongkan atau gunakan \"dikonfirmasi saat pemesanan\" hingga diverifikasi.",
     "Masukkan selepas pengesahan jualan untuk paparan katalog. Anda boleh nyatakan rujukan khusus (cth. \"25 hari bekerja selepas pengesahan pesanan\") — jangan gunakan janji samar seperti \"lebih kurang X minggu\". Biarkan kosong atau gunakan \"disahkan semasa pesanan\" sehingga disahkan."),
    ("Translation is taking longer than usual. Please wait or try again later.",
     "Terjemahan membutuhkan waktu lebih lama dari biasanya. Harap tunggu atau coba lagi nanti.",
     "Terjemahan mengambil masa lebih lama daripada biasa. Sila tunggu atau cuba lagi nanti."),
    ("Translation saved successfully", "Terjemahan berhasil disimpan", "Terjemahan berjaya disimpan"),
    ("Could not load data. Please try again.", "Tidak dapat memuat data. Silakan coba lagi.", "Tidak dapat memuatkan data. Sila cuba lagi."),
    ("Could not delete. Please try again.", "Tidak dapat menghapus. Silakan coba lagi.", "Tidak dapat memadam. Sila cuba lagi."),
    ("Could not upload. Please try again.", "Tidak dapat mengunggah. Silakan coba lagi.", "Tidak dapat muat naik. Sila cuba lagi."),
    ("Base price must be greater than zero.", "Harga dasar harus lebih dari nol.", "Harga asas mesti lebih daripada sifar."),
    ("Cannot activate a product with zero stock. Please add stock first.",
     "Tidak dapat mengaktifkan produk dengan stok nol. Tambahkan stok terlebih dahulu.",
     "Tidak dapat mengaktifkan produk dengan stok sifar. Sila tambah stok dahulu."),
    ("Minimum order quantity must be at least 1.", "Kuantitas pesanan minimum minimal 1.", "Kuantiti pesanan minimum mestilah sekurang-kurangnya 1."),
    ("Shipping street address is required.", "Alamat jalan pengiriman wajib diisi.", "Alamat jalan penghantaran diperlukan."),
    ("Shipping city is required.", "Kota pengiriman wajib diisi.", "Bandar penghantaran diperlukan."),
    ("Target country is required.", "Negara tujuan wajib diisi.", "Negara destinasi diperlukan."),
    ("Invalid status transition. Allowed: draft → active, active ↔ inactive.",
     "Transisi status tidak valid. Diizinkan: draft → active, active ↔ inactive.",
     "Peralihan status tidak sah. Dibenarkan: draft → active, active ↔ inactive."),
    ("We use cookies to enhance your browsing experience, analyze site traffic, and personalize content. By clicking 'Accept All', you consent to our use of all cookies. You can choose 'Essential Only' to reject non-essential cookies.",
     "Kami menggunakan cookie untuk meningkatkan pengalaman browsing, menganalisis lalu lintas situs, dan mempersonalisasi konten. Dengan mengeklik 'Terima Semua', Anda setuju penggunaan semua cookie. Pilih 'Esensial Saja' untuk menolak cookie non-esensial.",
     "Kami menggunakan kuki untuk meningkatkan pengalaman melayari, menganalisis trafik laman, dan memperibadikan kandungan. Dengan mengklik 'Terima Semua', anda bersetuju dengan penggunaan semua kuki. Pilih 'Asas Sahaja' untuk menolak kuki bukan asas."),
]
