#!/usr/bin/env python3
"""Build vi_admin_phrases.json from vi_admin_remaining.json with full Vietnamese translations."""

import json
from pathlib import Path

REMAINING = Path(__file__).resolve().parent / "vi_admin_remaining.json"
OUTPUT = Path(__file__).resolve().parent / "vi_admin_phrases.json"

# Full dot-path translations for all 541 remaining keys
PATH_TRANSLATIONS: dict[str, str] = {
    "admin.logout": "Đăng xuất",
    "admin.theme.dark": "Chế độ tối",
    "admin.theme.light": "Chế độ sáng",
    "admin.a11y.closeNav": "Đóng menu thanh bên",
    "admin.a11y.toggleSidebar": "Mở rộng hoặc thu gọn thanh bên",
    "admin.nav.webhooks": "Webhooks",
    "admin.reports.rfm": "Phân tích RFM",
    "admin.reports.inventory_health": "Sức khỏe tồn kho",
    "admin.reports.profit_loss": "Lãi & Lỗ",
    "admin.reports.inquiry_conversion": "Chuyển đổi yêu cầu báo giá",
    "admin.reports.col_id": "ID",
    "admin.reports.col_email": "Email",
    "admin.reports.col_qty": "SL",
    "admin.reports.col_frequency": "Tần suất",
    "admin.reports.col_monetary": "Giá trị",
    "admin.reports.col_segment": "Phân khúc",
    "admin.reports.col_days_inactive": "Số ngày không hoạt động",
    "admin.reports.col_revenue": "Doanh thu",
    "admin.reports.col_cost": "Chi phí",
    "admin.reports.col_inquiries": "Yêu cầu báo giá",
    "admin.reports.col_converted": "Đã chuyển đổi",
    "admin.reports.col_rate": "Tỷ lệ",
    "admin.analytics.revenue_trends": "Xu hướng doanh thu",
    "admin.analytics.conversion_funnel": "Chuyển đổi yêu cầu báo giá",
    "admin.analytics.col_revenue": "Doanh thu",
    "admin.analytics.col_quantity": "Số lượng",
    "admin.analytics.range_12m": "12 tháng",
    "admin.analytics.inquiry_conversion": "Chuyển đổi yêu cầu báo giá",
    "admin.analytics.revenue_label": "Doanh thu",
    "admin.analytics.orders_label": "Đơn hàng",
    "admin.financial.outstanding_invoices": "Hóa đơn chưa thanh toán",
    "admin.financial.revenue": "Doanh thu",
    "admin.financial.outstanding_list": "Danh sách hóa đơn chưa thanh toán",
    "admin.financial.col_invoice_no": "Số hóa đơn",
    "admin.financial.overdue": "Quá hạn",
    "admin.financial.due_soon": "Sắp đến hạn",
    "admin.users.col_company": "Công ty",
    "admin.users.create_user": "Tạo người dùng",
    "admin.users.first_name": "Tên",
    "admin.users.last_name": "Họ",
    "admin.users.email": "Email",
    "admin.users.role_admin": "Quản trị viên",
    "admin.users.role_superadmin": "Siêu quản trị viên",
    "admin.inquiries.new_inquiry": "Yêu cầu mới",
    "admin.inquiries.col_products": "Sản phẩm",
    "admin.inquiries.edit_inquiry": "Sửa yêu cầu báo giá",
    "admin.inquiries.user_id": "ID người dùng (tùy chọn)",
    "admin.inquiries.contact_person": "Người liên hệ",
    "admin.inquiries.email": "Email",
    "admin.inquiries.whatsapp": "WhatsApp",
    "admin.inquiries.estimated_quantity": "Số lượng ước tính",
    "admin.inquiries.interested_products": "Sản phẩm quan tâm (phân tách bằng dấu phẩy)",
    "admin.inquiries.product_ids": "ID sản phẩm liên kết",
    "admin.inquiries.oem_needed": "Cần OEM",
    "admin.inquiries.message": "Tin nhắn",
    "admin.inquiries.assignment": "Phân công",
    "admin.inquiries.assignee_placeholder": "ID người được gán",
    "admin.inquiries.assign": "Gán",
    "admin.inquiries.assigning": "Đang gán...",
    "admin.inquiries.ai_analysis": "Phân tích AI",
    "admin.inquiries.analyzing": "Đang phân tích...",
    "admin.inquiries.risk": "Rủi ro",
    "admin.inquiries.action": "Hành động",
    "admin.inquiries.quote": "Báo giá",
    "admin.inquiries.products_placeholder": "Sản phẩm (phân tách bằng dấu phẩy)",
    "admin.inquiries.notes_placeholder": "Ghi chú khách hàng",
    "admin.inquiries.submit_quote": "Gửi báo giá",
    "admin.inquiries.submitting": "Đang gửi...",
    "admin.inquiries.validation_required": "Công ty, người liên hệ và email là bắt buộc.",
    "admin.inquiries.validation_quote_amount": "Số tiền báo giá phải lớn hơn 0.",
    "admin.inquiries.assigned_success": "Đã phân công yêu cầu báo giá thành công.",
    "admin.orders.new_order": "Đơn hàng mới",
    "admin.orders.edit_order": "Sửa đơn hàng",
    "admin.orders.create_order": "Tạo đơn hàng",
    "admin.orders.user_id": "ID người dùng",
    "admin.orders.inquiry_id": "ID yêu cầu báo giá",
    "admin.orders.subtotal": "Tạm tính",
    "admin.orders.shipping": "Vận chuyển",
    "admin.orders.cogs": "COGS",
    "admin.orders.tracking_number": "Mã vận đơn",
    "admin.orders.items": "Mặt hàng đơn hàng",
    "admin.orders.item_product_id": "ID sản phẩm",
    "admin.orders.item_qty": "SL",
    "admin.orders.item_spec": "Thông số kỹ thuật",
    "admin.orders.shipping_address": "Địa chỉ giao hàng",
    "admin.orders.addr_street": "Đường",
    "admin.orders.addr_state": "Bang/Tỉnh",
    "admin.orders.addr_country": "Quốc gia",
    "admin.orders.filter_all": "Tất cả",
    "admin.orders.filter_user": "ID người dùng",
    "admin.orders.preview": "Xem trước",
    "admin.orders.ai_topic_placeholder": "Nhập chủ đề để AI viết...",
    "admin.orders.convert_to_md": "Chuyển sang MD",
    "admin.orders.col_quantity": "SL",
    "admin.orders.col_subtotal": "Tạm tính",
    "admin.orders.no_items": "Không tìm thấy mặt hàng",
    "admin.orders.compliance_verified": "Đã xác minh tuân thủ",
    "admin.orders.inventory_warnings": "Cảnh báo tồn kho",
    "admin.orders.activity_payment_confirm": "Đã xác nhận thanh toán",
    "admin.orders.create_trade": "Tạo giao dịch từ đơn hàng",
    "admin.orders.creating_trade": "Đang tạo...",
    "admin.orders.trade_created": "Đã tạo giao dịch thương mại thành công.",
    "admin.orders.view_trade": "Xem giao dịch",
    "admin.orders.payment": "Thanh toán",
    "admin.orders.loading_payments": "Đang tải thanh toán...",
    "admin.orders.no_payments": "Không tìm thấy thanh toán",
    "admin.orders.no_activity": "Không có hoạt động ghi nhận",
    "admin.orders.confirm_refund": "Bạn có chắc muốn hoàn tiền thanh toán này?",
    "admin.orders.inquiry": "Yêu cầu báo giá",
    "admin.orders.fulfillment_warehouse": "ID kho",
    "admin.orders.fulfillment_ship": "Giao hàng",
    "admin.orders.fulfillment_tracking": "Mã vận đơn",
    "admin.orders.fulfillment_carrier": "Hãng vận chuyển",
    "admin.orders.fulfillment_no_data": "Chưa có thực hiện đơn.",
    "admin.orders.fulfillment_created": "Đã tạo thực hiện đơn.",
    "admin.orders.fulfillment_shipped": "Đã đánh dấu đã giao.",
    "admin.orders.fulfillment_delivered": "Đã xác nhận giao hàng.",
    "admin.inquiryDetail.submitted_on": "Gửi ngày",
    "admin.inquiryDetail.user": "Người dùng",
    "admin.inquiryDetail.contact_person": "Người liên hệ",
    "admin.inquiryDetail.email": "Email",
    "admin.inquiryDetail.whatsapp": "WhatsApp",
    "admin.inquiryDetail.estimated_quantity": "Số lượng ước tính",
    "admin.inquiryDetail.linked_product_ids": "ID sản phẩm liên kết",
    "admin.inquiryDetail.oem_needed": "Cần OEM",
    "admin.inquiryDetail.message": "Tin nhắn",
    "admin.inquiryDetail.assigned_to": "Được gán cho",
    "admin.inquiryDetail.packaging_requirements": "Yêu cầu bao bì",
    "admin.inquiryDetail.ai_compliance_check": "Kiểm tra tuân thủ AI",
    "admin.inquiryDetail.passed": "Đạt",
    "admin.inquiryDetail.quotation": "Báo giá",
    "admin.inquiryDetail.submit_quote": "Gửi báo giá",
    "admin.inquiryDetail.submitting": "Đang gửi...",
    "admin.inquiryDetail.ai_quotation_draft": "Bản nháp báo giá AI",
    "admin.inquiryDetail.convert_description": "Chuyển yêu cầu báo giá này thành đơn hàng cho khách hàng.",
    "admin.inquiryDetail.converted_success": "Đã chuyển đổi yêu cầu báo giá thành công. ",
    "admin.inquiryDetail.no_activity": "Không có hoạt động ghi nhận",
    "admin.inquiryDetail.valid_until": "Có hiệu lực đến",
    "admin.inquiryDetail.shipping_street": "Đường",
    "admin.inquiryDetail.shipping_state": "Bang/Tỉnh",
    "admin.inquiryDetail.shipping_zip": "Mã bưu điện",
    "admin.inquiryDetail.shipping_country": "Quốc gia",
    "admin.inquiryDetail.confirm_specs_title": "Quản trị viên xác nhận thông số",
    "admin.inquiryDetail.packaging_type": "Loại bao bì",
    "admin.inquiryDetail.packaging_size": "Kích thước bao bì",
    "admin.inquiryDetail.customer_already_confirmed": "Khách hàng đã xác nhận",
    "admin.inquiryDetail.confirm_specs_success": "Đã xác nhận thông số",
    "admin.inquiryDetail.current_packaging": "Thông số bao bì hiện tại",
    "admin.inquiryDetail.packaging_not_set": "Chưa thiết lập",
    "admin.inquiryDetail.no_files": "Không có tệp",
    "admin.inquiryDetail.negotiation": "Thương lượng",
    "admin.inquiryDetail.negotiation_description": "Phản đề xuất và thương lượng giá với người mua.",
    "admin.inquiryDetail.create_offer": "Tạo đề xuất",
    "admin.inquiryDetail.offer_quantity": "Số lượng",
    "admin.inquiryDetail.offer_incoterms": "Incoterms",
    "admin.inquiryDetail.offer_payment_terms": "Điều khoản thanh toán",
    "admin.inquiryDetail.offer_delivery_date": "Ngày giao hàng",
    "admin.inquiryDetail.offer_valid_until": "Có hiệu lực đến",
    "admin.inquiryDetail.offer_message": "Tin nhắn",
    "admin.inquiryDetail.offer_by": "Bởi",
    "admin.inquiryDetail.offer_round": "Đề xuất",
    "admin.inquiryDetail.offer_submitting": "Đang gửi...",
    "admin.products.col_moq": "MOQ",
    "admin.products.slug": "Slug",
    "admin.products.moq": "MOQ",
    "admin.products.oem": "OEM",
    "admin.products.halal": "Halal",
    "admin.products.field_kosher": "Kosher",
    "admin.products.field_protein_g": "Protein (g)",
    "admin.products.packaging_placeholder": "flow-wrap, foil, box, bag, jar",
    "admin.products.gmo_option_gmo": "GMO",
    "admin.products.gmo_option_non_gmo": "Non-GMO",
    "admin.products.gmo_option_gmo_free_certified": "GMO-Free Certified",
    "admin.products.locale_tab_en": "English",
    "admin.products.locale_tab_zh": "Chinese",
    "admin.products.locale_tab_ar": "Arabic",
    "admin.products.locale_tab_ko": "Korean",
    "admin.products.locale_tab_ja": "Japanese",
    "admin.products.locale_tab_zh-tw": "Traditional Chinese",
    "admin.products.locale_tab_th": "Thai",
    "admin.products.locale_tab_vi": "Vietnamese",
    "admin.products.locale_tab_id": "Indonesian",
    "admin.products.locale_tab_ms": "Malay",
    "admin.products.cost_logistics": "Logistics",
    "admin.content.add_content": "Thêm nội dung",
    "admin.content.tab_posts": "Bài viết blog",
    "admin.content.tab_cases": "Nghiên cứu điển hình",
    "admin.content.col_meta": "Danh mục/Ngành",
    "admin.content.category_general": "Chung",
    "admin.content.create_content": "Tạo nội dung",
    "admin.content.content_slug": "Slug",
    "admin.content.post_category": "Danh mục",
    "admin.content.content_thumbnail": "Ảnh thu nhỏ",
    "admin.content.og_image": "Ảnh OG (Chia sẻ mạng xã hội)",
    "admin.content.og_image_hint": "Tùy chọn. Khuyến nghị 1200×630 cho xem trước mạng xã hội.",
    "admin.content.url_or_upload": "URL hoặc tải lên",
    "admin.content.author_name": "Tên tác giả",
    "admin.content.author_bio": "Tiểu sử tác giả",
    "admin.content.case_client": "Tên khách hàng",
    "admin.content.case_location": "Địa điểm",
    "admin.content.case_timeline": "Mốc thời gian",
    "admin.content.case_images": "Ảnh (URL phân tách bằng dấu phẩy)",
    "admin.content.post_excerpt": "Trích dẫn",
    "admin.content.ai_topic_label": "Chủ đề / Mô tả",
    "admin.content.ai_generate": "Tạo bằng AI",
    "admin.content.post_content": "Nội dung",
    "admin.content.editor_placeholder": "Bắt đầu viết...",
    "admin.content.case_content": "Nội dung case study",
    "admin.content.case_result": "Kết quả",
    "admin.content.ai_create_drawer_title": "Tạo nội dung bằng AI",
    "admin.content.ai_empty_preview": "Nhập chủ đề và nhấn Tạo bản nháp tiếng Trung. Xem lại, sau đó xuất bản với đầy đủ bản dịch.",
    "admin.content.ai_generate_zh_draft": "Tạo bản nháp tiếng Trung",
    "admin.content.inline_ai_title": "Sửa vùng chọn",
    "admin.content.inline_ai_placeholder": "Mô tả cách thay đổi vùng chọn…",
    "admin.content.inline_ai_selection": "Vùng chọn",
    "admin.content.inline_ai_after": "Sau",
    "admin.content.ai_publish_translating": "Đang dịch & xuất bản...",
    "admin.content.ai_published_success": "Đã dịch và xuất bản bài viết",
    "admin.content.ai_revise_title": "Sửa đổi có mục tiêu bằng AI",
    "admin.content.ai_revise_hint": "Chọn văn bản trong phần thân hoặc chọn phạm vi, sau đó mô tả chỉnh sửa (sửa cục bộ kiểu Cursor).",
    "admin.content.ai_revise_placeholder": "vd. Rút ngắn tiêu đề; thêm chi tiết tuân thủ EU ở đoạn 2; dùng giọng văn chuyên nghiệp hơn…",
    "admin.content.ai_revise_selected": "Đoạn trích đã chọn",
    "admin.content.ai_revise_scope": "Phạm vi sửa đổi",
    "admin.content.ai_revise_scope_auto": "Tự động phát hiện",
    "admin.content.ai_revise_scope_excerpt": "Trích dẫn",
    "admin.content.ai_revise_scope_content": "Nội dung chính",
    "admin.content.ai_revise_scope_meta": "Danh mục / thẻ",
    "admin.content.ai_revise_apply": "Áp dụng sửa đổi",
    "admin.content.ai_revise_failed": "Sửa đổi AI thất bại — hãy diễn đạt lại hướng dẫn",
    "admin.content.translations_label": "Bản dịch",
    "admin.content.ai_translate": "Dịch bằng AI",
    "admin.content.trans_title_placeholder": "Để trống để dùng tiêu đề mặc định",
    "admin.content.trans_author_bio_placeholder": "Để trống để dùng tiểu sử tác giả mặc định",
    "admin.categories.col_slug": "Slug",
    "admin.categories.slug": "Slug",
    "admin.certifications.add_certification": "Thêm chứng nhận",
    "admin.certifications.col_certification": "Chứng nhận",
    "admin.certifications.col_abbreviation": "Viết tắt",
    "admin.certifications.col_valid_until": "Có hiệu lực đến",
    "admin.certifications.edit_certification": "Sửa chứng nhận",
    "admin.certifications.abbreviation": "Viết tắt",
    "admin.certifications.description_label": "Mô tả",
    "admin.certifications.valid_until": "Có hiệu lực đến",
    "admin.certifications.badge_url": "URL huy hiệu",
    "admin.companies.search_placeholder": "Tìm theo tên...",
    "admin.companies.all_statuses": "Tất cả trạng thái",
    "admin.companies.verified": "Đã xác minh",
    "admin.companies.col_tax_id": "Mã số thuế",
    "admin.companies.col_payment_terms": "Điều khoản thanh toán",
    "admin.companies.col_verified_at": "Xác minh lúc",
    "admin.companies.company_details": "Chi tiết doanh nghiệp",
    "admin.companies.tax_id": "Mã số thuế",
    "admin.companies.registration_number": "Số đăng ký",
    "admin.companies.address": "Địa chỉ",
    "admin.companies.website": "Trang web",
    "admin.companies.view_document": "Xem tài liệu",
    "admin.companies.verified_at": "Xác minh lúc",
    "admin.companies.reviewed_by": "Được duyệt bởi",
    "admin.companies.kyb_notes": "Ghi chú KYB",
    "admin.companies.credit_pricing": "Tín dụng & Giá",
    "admin.companies.payment_terms": "Điều khoản thanh toán",
    "admin.companies.linked_users": "Người dùng liên kết",
    "admin.companies.user_email": "Email",
    "admin.companies.no_users": "Không có người dùng liên kết",
    "admin.companies.status_management": "Quản lý trạng thái",
    "admin.companies.kyb_status": "Trạng thái KYB",
    "admin.trades.all_statuses": "Tất cả trạng thái",
    "admin.trades.in_progress": "Đang xử lý",
    "admin.trades.col_transaction": "Giao dịch",
    "admin.trades.transaction": "Giao dịch",
    "admin.trades.created_on": "Tạo ngày",
    "admin.trades.incoterms": "Incoterms",
    "admin.trades.port_of_loading": "Cảng xếp hàng",
    "admin.trades.port_of_discharge": "Cảng dỡ hàng",
    "admin.trades.delivery_terms": "Điều khoản giao hàng",
    "admin.trades.doc_name": "Tên tài liệu",
    "admin.trades.doc_type": "Loại",
    "admin.trades.order_id": "ID đơn hàng",
    "admin.trades.inquiry_id": "ID yêu cầu báo giá",
    "admin.trades.no_documents": "Chưa có tài liệu.",
    "admin.trades.view_detail": "Xem chi tiết",
    "admin.trades.ai_assistant": "Trợ lý AI",
    "admin.trades.expand": "Mở rộng",
    "admin.trades.tools_called": "Công cụ đã gọi",
    "admin.trades.ai_typing": "AI đang suy nghĩ...",
    "admin.trades.ai_generating": "AI đang tạo...",
    "admin.trades.ai_generate_doc": "Tạo tài liệu bằng AI",
    "admin.trades.ai_stream_interrupted": "Luồng bị gián đoạn",
    "admin.trades.ai_generate_prompt": "Tạo {type} cho giao dịch thương mại này.",
    "admin.trades.export_xlsx": "Xuất XLSX",
    "admin.trades.quick_generate": "Tạo tài liệu nhanh",
    "admin.trades.settlement_amount": "Số tiền phải trả",
    "admin.trades.compliance": "Tuân thủ",
    "admin.trades.no_compliance": "Không có yêu cầu tuân thủ.",
    "admin.trades.compliance_item": "Yêu cầu",
    "admin.pricing.price_lists": "Bảng giá",
    "admin.pricing.product_pricing": "Giá sản phẩm",
    "admin.pricing.no_price_lists": "Không tìm thấy bảng giá.",
    "admin.pricing.no_prices": "Chưa thiết lập quy tắc giá",
    "admin.pricing.col_products": "Sản phẩm",
    "admin.pricing.edit_price_list": "Sửa bảng giá",
    "admin.pricing.confirm_delete_price_list": "Xóa bảng giá này?",
    "admin.pricing.min_qty": "SL tối thiểu",
    "admin.pricing.select_price_list": "Chọn bảng giá...",
    "admin.oemProjects.search_placeholder": "Tìm theo ID dự án...",
    "admin.oemProjects.all_statuses": "Tất cả trạng thái",
    "admin.oemProjects.inquiry": "Yêu cầu báo giá",
    "admin.oemProjects.sampling": "Lấy mẫu",
    "admin.oemProjects.quotation": "Báo giá",
    "admin.oemProjects.production": "Sản xuất",
    "admin.oemProjects.col_project": "Dự án",
    "admin.oemProjects.project": "Dự án",
    "admin.oemProjects.created_on": "Tạo ngày",
    "admin.oemProjects.target_market": "Thị trường mục tiêu",
    "admin.oemProjects.assigned_to": "Được gán cho",
    "admin.oemProjects.shape": "Hình dạng",
    "admin.oemProjects.moq": "MOQ",
    "admin.oemProjects.requirements_notes": "Ghi chú yêu cầu",
    "admin.oemProjects.samples": "Mẫu",
    "admin.oemProjects.requested_date": "Đã yêu cầu",
    "admin.oemProjects.shipped_date": "Đã giao",
    "admin.oemProjects.view_detail": "Xem chi tiết",
    "admin.user_detail.admin_actions": "Thao tác quản trị",
    "admin.user_detail.edit_profile": "Sửa hồ sơ khách hàng",
    "admin.user_detail.first_name": "Tên",
    "admin.user_detail.last_name": "Họ",
    "admin.user_detail.danger_zone": "Vùng nguy hiểm",
    "admin.user_detail.deleting": "Đang xóa...",
    "admin.user_detail.delete_user": "Xóa người dùng",
    "admin.user_detail.role_option_admin": "Quản trị viên",
    "admin.inventory.col_sku": "SKU",
    "admin.inventory.col_moq": "MOQ",
    "admin.inventory.from_to": "{from} → {to}",
    "admin.inventory.batch_edit_field_moq": "MOQ",
    "admin.inventory.export_filename": "inventory",
    "admin.shipments.status_exception": "Ngoại lệ",
    "admin.shipments.col_carrier": "Hãng vận chuyển",
    "admin.shipments.col_destination": "Điểm đến",
    "admin.shipments.col_eta": "ETA",
    "admin.shipments.carrier": "Hãng vận chuyển",
    "admin.shipments.tracking_number": "Mã vận đơn",
    "admin.shipments.date_to": "Đến ngày",
    "admin.shipments.filter_status": "Lọc trạng thái",
    "admin.shipments.csv_headers": "Mã vận đơn,Đơn hàng,Hãng vận chuyển,Điểm đến,Trạng thái,ETA,Đã giao",
    "admin.shipments.dispatch_success": "Đã gửi lô hàng.",
    "admin.shipments.delivery_success": "Đã xác nhận giao hàng.",
    "admin.shipments.add_event": "Thêm sự kiện",
    "admin.shipments.event_location": "Địa điểm",
    "admin.shipments.event_description": "Mô tả",
    "admin.shipments.loading_timeline": "Đang tải dòng thời gian...",
    "admin.trade_shipments.col_bol": "Số B/L",
    "admin.trade_shipments.col_trade": "ID giao dịch",
    "admin.returns.filter_all": "Tất cả trạng thái",
    "admin.returns.col_reason": "Lý do",
    "admin.returns.status_received": "Đã nhận",
    "admin.returns.reject_reason": "Lý do từ chối",
    "admin.returns.receive_success": "Đã nhận hàng trả.",
    "admin.returns.refund_success": "Đã xử lý hoàn tiền.",
    "admin.invoices.create_invoice": "Tạo hóa đơn",
    "admin.invoices.sent": "Đã gửi",
    "admin.invoices.status_sent": "Đã gửi",
    "admin.invoices.status_overdue": "Quá hạn",
    "admin.invoices.status_voided": "Đã hủy bỏ",
    "admin.invoices.status_cancelled": "Đã hủy",
    "admin.invoices.date_from": "Từ ngày",
    "admin.invoices.filter_status": "Lọc trạng thái",
    "admin.invoices.col_invoice": "Hóa đơn",
    "admin.invoices.edit_invoice": "Sửa hóa đơn",
    "admin.invoices.paid_amount_line": "Đã thanh toán: {currency} {amount}",
    "admin.invoices.invoice_preview": "Xem trước hóa đơn",
    "admin.invoices.bill_to": "Thanh toán cho",
    "admin.invoices.credit_note_heading": "GHI CÓ",
    "admin.invoices.csv_headers": "Số HĐ,Đơn hàng,Khách hàng,Số tiền,Đã trả,Trạng thái,Ngày,Hạn thanh toán",
    "admin.invoices.from_order": "Từ đơn hàng",
    "admin.invoices.export_doc": "Xuất DOCX",
    "admin.staff.col_email": "Email",
    "admin.staff.never": "Không bao giờ",
    "admin.staff.no_activity": "Không có hoạt động gần đây.",
    "admin.staff.col_action": "Hành động",
    "admin.staff.col_details": "Chi tiết",
    "admin.staff.just_now": "vừa xong",
    "admin.staff.hours_ago": "{count} giờ trước",
    "admin.staff.days_ago": "{count} ngày trước",
    "admin.auditLog.filter_all_types": "Tất cả loại thực thể",
    "admin.auditLog.entity_inquiry": "Yêu cầu báo giá",
    "admin.auditLog.entity_user": "Người dùng",
    "admin.auditLog.entity_trade": "Giao dịch",
    "admin.auditLog.action_create": "Tạo",
    "admin.auditLog.action_update": "Cập nhật",
    "admin.auditLog.action_delete": "Xóa",
    "admin.auditLog.action_status_change": "Thay đổi trạng thái",
    "admin.auditLog.col_action": "Hành động",
    "admin.auditLog.col_ip": "Địa chỉ IP",
    "admin.auditLog.just_now": "vừa xong",
    "admin.auditLog.hours_ago": "{count} giờ trước",
    "admin.auditLog.days_ago": "{count} ngày trước",
    "admin.settings.saved": "Đã lưu cài đặt thành công.",
    "admin.settings.tab_general": "Chung",
    "admin.settings.tab_email": "Email",
    "admin.settings.tab_trade": "Thương mại",
    "admin.settings.tab_notifications": "Thông báo",
    "admin.docLabels.commercial_invoice": "Hóa đơn thương mại",
    "admin.docLabels.bill_of_lading": "Vận đơn",
    "admin.docLabels.sales_contract": "Hợp đồng bán hàng",
    "admin.docLabels.packing_list": "Phiếu đóng gói",
    "admin.docLabels.cert_of_origin": "Giấy chứng nhận xuất xứ",
    "admin.docLabels.pi_no": "Số PI",
    "admin.docLabels.ci_no": "Số CI",
    "admin.docLabels.bl_no": "Số B/L",
    "admin.docLabels.contract_no": "Số hợp đồng",
    "admin.docLabels.pl_no": "Số PL",
    "admin.docLabels.incoterms": "Incoterms",
    "admin.docLabels.buyer_name": "Tên người mua",
    "admin.docLabels.seller_name": "Tên người bán",
    "admin.docLabels.payment_terms": "Điều khoản thanh toán",
    "admin.docLabels.pi_reference": "Tham chiếu PI",
    "admin.docLabels.consignee": "Người nhận hàng",
    "admin.docLabels.notify_party": "Bên được thông báo",
    "admin.docLabels.carrier": "Hãng vận chuyển",
    "admin.docLabels.vessel_voyage": "Tàu/Chuyến",
    "admin.docLabels.port_of_loading": "Cảng xếp hàng",
    "admin.docLabels.port_of_discharge": "Cảng dỡ hàng",
    "admin.docLabels.freight_terms": "Điều khoản cước",
    "admin.docLabels.gross_weight": "Trọng lượng tổng (kg)",
    "admin.docLabels.no_of_packages": "Số kiện",
    "admin.docLabels.delivery_date": "Ngày giao hàng",
    "admin.docLabels.special_terms": "Điều khoản đặc biệt",
    "admin.docLabels.country_of_origin": "Nước xuất xứ",
    "admin.docLabels.destination_country": "Nước đích",
    "admin.docLabels.issuing_authority": "Cơ quan cấp",
    "admin.docLabels.batch_number": "Số lô",
    "admin.docLabels.production_date": "Ngày sản xuất",
    "admin.docLabels.expiry_date": "Ngày hết hạn",
    "admin.docLabels.inspection_result": "Kết quả kiểm tra",
    "admin.order_prefix": "Đơn hàng #",
    "admin.col_id": "ID",
    "admin.translations.search_placeholder": "Tìm khóa hoặc giá trị...",
    "admin.translations.all_locales": "Tất cả ngôn ngữ",
    "admin.translations.col_key": "Khóa",
    "admin.translations.col_locale": "Ngôn ngữ",
    "admin.translations.col_value": "Giá trị",
    "admin.translations.label_key": "Khóa",
    "admin.translations.label_locale": "Ngôn ngữ",
    "admin.translations.label_value": "Giá trị",
    "admin.translations.create_title": "Tạo bản dịch",
    "admin.translations.update_failed": "Cập nhật bản dịch thất bại",
    "admin.translations.export_failed": "Xuất bản dịch thất bại",
    "admin.ai.coming_soon": "Bảng tính năng AI sắp ra mắt.",
    "admin.ai.clear_chat": "Xóa cuộc trò chuyện",
    "admin.ai.start_conversation": "Bắt đầu trò chuyện với AI Agent",
    "admin.ai.stop": "Dừng",
    "admin.ai.tool_call_history": "Lịch sử gọi công cụ",
    "admin.ai.model_label": "Model",
    "admin.ai.temperature_label": "Nhiệt độ",
    "admin.ai.agent_mode": "Chế độ Agent",
    "admin.ai.mode_plan": "Plan-Execute-Replan",
    "admin.ai.mode_trade": "Trợ lý thương mại",
    "admin.ai.mode_chatbot": "Chatbot (tùy chọn đơn hàng)",
    "admin.ai.mode_recommend": "Gợi ý sản phẩm",
    "admin.ai.mode_translate": "Dịch",
    "admin.ai.order_context": "Ngữ cảnh đơn hàng",
    "admin.ai_help.content_inline_edit.body": "1. Chọn văn bản trong tiêu đề, trích dẫn hoặc phần thân.\n2. Nhấn Ctrl+K (Mac: ⌘K) để mở trình sửa nổi.\n3. Mô tả thay đổi (vd. thêm chi tiết tuân thủ, rút ngắn tiêu đề).\n4. Xem trước diff trước/sau — Chấp nhận hoặc Từ chối.\n5. Lặp lại cho đến khi hài lòng, rồi xuất bản.",
    "admin.ai_help.content_modal_ai.body": "Khi sửa nội dung, nhập chủ đề và nhấn Tạo bằng AI để điền tiêu đề, nội dung, v.v. (bản nháp tiếng Trung, không tự dịch).\nSau khi lưu, dùng Dịch bằng AI trong phần bản dịch cho các ngôn ngữ khác.",
    "admin.ai_help.content_translate.body": "Khi sửa nội dung đã lưu, nhấn Dịch bằng AI trong phần Bản dịch.\nCác trường nguồn (thường là tiếng Trung) được dịch sang en/ko/ar/ja/th/vi/id/ms.\nXem lại từng tab ngôn ngữ và lưu.",
    "admin.ai_help.products_translate.body": "Khi sửa sản phẩm, nhấn Dịch bằng AI trong phần Bản dịch.\nTên, tóm tắt, mô tả, thành phần, v.v. được dịch từ locale chính.\nXem lại các tab ngôn ngữ trước khi lưu.",
    "admin.ai_help.ai_console.body": "Chọn chế độ Agent bên phải, rồi trò chuyện:\n• Chatbot: Hỏi đáp; tùy chọn ngữ cảnh đơn hàng.\n• Plan-Execute-Replan / B2B Coordinator / Trợ lý thương mại: agent truyền luồng.\n• Gợi ý / Tìm kiếm / Dịch / Phân tích yêu cầu / Tạo báo giá: JSON một lần.\nVới Chatbot, chọn đơn hàng ở thanh bên để thảo luận đơn đó.",
    "admin.ai_help.xlsx_translate.body": "Tải Excel lên, chọn chế độ dịch đơn hoặc hàng loạt.\nAI dịch tiêu đề hoặc khóa cột đã chọn — hữu ích cho báo cáo và bảng thuật ngữ.\nTải kết quả xuống; thử mẫu nhỏ trước khi chạy hàng loạt.",
    "admin.ai_help.trades_assistant.body": "Trò chuyện về giao dịch này — tài liệu, tuân thủ, logistics.\nAgent có thể gọi công cụ thương mại; phản hồi truyền luồng trong panel chat.\nDùng Tạo tài liệu bằng AI bên dưới để soạn nháp PI/CI/SC.",
    "admin.ai_help.trades_generate_doc.body": "Chọn loại tài liệu (PI, CI, SC, v.v.) và ngữ cảnh tùy chọn.\nAI soạn nháp từ dữ liệu giao dịch hiện tại và lưu vào hệ thống.\nLuôn kiểm tra các trường trong danh sách tài liệu trước khi gửi cho khách.",
    "admin.ai_help.inquiries_quotation.body": "Tạo bản nháp báo giá từ sản phẩm và yêu cầu trong yêu cầu báo giá.\nBản nháp chỉ mang tính tham khảo — nhập số tiền chính thức và thời hạn hiệu lực trong biểu mẫu bên dưới trước khi gửi.",
    "admin.ai_help.inquiries_compliance.body": "Tóm tắt AI về cờ tuân thủ/rủi ro của yêu cầu báo giá khi đã cấu hình.\nChỉ để tham khảo bán hàng — không thay thế đánh giá pháp lý/tuân thủ.",
    "admin.ai_help.inventory_import_ai.body": "Sau khi tải file Excel kho/sản phẩm, AI đề xuất ánh xạ cột → trường.\nXem banner xanh và điều chỉnh ánh xạ bên dưới trước khi xác nhận nhập.",
    "admin.oem.tab_flows": "Quy trình",
    "admin.oem.new_flow": "+ Quy trình mới",
    "admin.oem.no_flows": "Chưa có quy trình.",
    "admin.oem.no_projects": "Chưa có dự án OEM.",
    "admin.oem.col_category": "Danh mục",
    "admin.oem.col_moq": "MOQ",
    "admin.oem.edit_flow": "Sửa quy trình",
    "admin.oem.new_flow_title": "Quy trình mới",
    "admin.oem.label_title": "Tiêu đề *",
    "admin.oem.label_type": "Loại",
    "admin.oem.label_description": "Mô tả",
    "admin.oem.label_timeline": "Mốc thời gian",
    "admin.oem.label_category": "Danh mục",
    "admin.oem.label_thumbnail": "URL ảnh thu nhỏ",
    "admin.oem.label_moq": "MOQ",
    "admin.oem.type_quick_odm": "Quick ODM",
    "admin.channels.price_multiplier": "Hệ số giá",
    "admin.channels.type_marketplace": "Sàn thương mại",
    "admin.channels.type_webstore": "Cửa hàng web",
    "admin.channels.fulfillment_self": "Tự thực hiện",
    "admin.channels.fulfillment_3pl": "3PL",
    "admin.webhooks.tab_configs": "Cấu hình",
    "admin.webhooks.tab_deliveries": "Giao hàng",
    "admin.webhooks.url": "URL",
    "admin.webhooks.events": "Sự kiện",
    "admin.webhooks.no_deliveries": "Không có nhật ký giao.",
    "admin.webhooks.col_url": "URL",
    "admin.webhooks.col_events": "Sự kiện",
    "admin.webhooks.col_status_code": "HTTP",
    "admin.webhooks.col_result": "Kết quả",
    "admin.hooks.tab_hooks": "Hooks",
    "admin.hooks.tab_events": "Sự kiện",
    "admin.hooks.tab_executions": "Thực thi",
    "admin.hooks.event_name": "Tên sự kiện",
    "admin.hooks.invalid_json": "Cấu hình JSON không hợp lệ.",
    "admin.hooks.no_executions": "Không tìm thấy thực thi.",
    "admin.hooks.col_payload": "Payload",
    "admin.organizations.members": "Thành viên",
    "admin.organizations.tab_orgs": "Tổ chức",
    "admin.organizations.tab_members": "Thành viên",
    "admin.organizations.no_members": "Không có thành viên.",
    "admin.organizations.select_org_placeholder": "Chọn tổ chức…",
    "admin.organizations.payment_terms": "Điều khoản thanh toán",
    "admin.organizations.user_id": "ID người dùng",
    "admin.organizations.role_approver": "Người phê duyệt",
    "admin.organizations.role_admin": "Quản trị viên",
    "admin.coupons.col_value": "Giá trị",
    "admin.xlsx.months": "Tháng",
    "admin.xlsx.trade_status": "Trạng thái giao dịch (tùy chọn)",
    "admin.xlsx.export_products": "Danh mục sản phẩm",
    "admin.xlsx.export_orders": "Đơn hàng",
    "admin.xlsx.export_revenue": "Báo cáo doanh thu",
    "admin.xlsx.export_trades": "Giao dịch thương mại",
    "admin.xlsx.exporting": "Đang xuất…",
    "admin.xlsx.export_success": "Đã bắt đầu tải xuống",
    "admin.xlsx.export_failed": "Xuất thất bại",
    "admin.xlsx.translate_hint": "Tải file .xlsx lên; các ô văn bản được dịch qua Trade Agent (pipeline translate_content).",
    "admin.xlsx.translate_mode_single": "Một ngôn ngữ",
    "admin.xlsx.source_auto": "Tự động phát hiện",
    "admin.xlsx.target_langs": "Ngôn ngữ đích",
    "admin.xlsx.select_file": "Chọn file .xlsx",
    "admin.xlsx.file_selected": "Đã chọn: {name}",
    "admin.xlsx.translate_btn": "Dịch & tải xuống",
    "admin.xlsx.translating": "Đang dịch…",
    "admin.xlsx.translate_success": "Đã tải file đã dịch",
    "admin.xlsx.invalid_file": "Vui lòng chọn file .xlsx",
    "admin.xlsx.select_target": "Chọn ít nhất một ngôn ngữ đích",
    "admin.xlsx.inventory_link": "Để nhập sản phẩm với ánh xạ cột AI, dùng Kho hàng → Nhập XLSX.",
    "admin.confirm_delete": "Xác nhận xóa?",
}


def main() -> None:
    remaining = json.loads(REMAINING.read_text(encoding="utf-8"))
    assert len(remaining) == 541, f"Expected 541 keys, got {len(remaining)}"

    missing = [k for k in remaining if k not in PATH_TRANSLATIONS]
    if missing:
        raise SystemExit(f"Missing translations for {len(missing)} keys: {missing[:5]}...")

    output: dict[str, str] = {}

    # Dot-path keys first
    for path, en_val in remaining.items():
        output[path] = PATH_TRANSLATIONS[path]

    # English source string keys (unique values from remaining)
    for en_val in remaining.values():
        if en_val not in output:
            # Find first path with this English value
            for path, src in remaining.items():
                if src == en_val:
                    output[en_val] = PATH_TRANSLATIONS[path]
                    break

    OUTPUT.write_text(json.dumps(output, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    path_count = len(remaining)
    string_count = sum(1 for k in output if not k.startswith("admin."))
    print(f"path_keys={path_count}, english_string_keys={string_count}, total_keys={len(output)}")


if __name__ == "__main__":
    main()
