#!/usr/bin/env python3
"""Generate i18n_admin_phrases_id_ms.json with complete id/ms translations."""

from __future__ import annotations

import json
from pathlib import Path

# English -> (Indonesian, Malay)
TRANSLATIONS: dict[str, tuple[str, str]] = {
    "#": ("#", "#"),
    "... and {n} more rows": ("... dan {n} baris lagi", "... dan {n} baris lagi"),
    "12 Months": ("12 Bulan", "12 Bulan"),
    "12M": ("12B", "12B"),
    "3 Months": ("3 Bulan", "3 Bulan"),
    "3M": ("3B", "3B"),
    "3PL": ("3PL", "3PL"),
    "6 Months": ("6 Bulan", "6 Bulan"),
    "6M": ("6B", "6B"),
    "A list of all users including their name, company, email, role, and status.": (
        "Daftar semua pengguna termasuk nama, perusahaan, email, peran, dan status.",
        "Senarai semua pengguna termasuk nama, syarikat, e-mel, peranan, dan status.",
    ),
    "AI Analysis": ("Analisis AI", "Analisis AI"),
    "AI Apps": ("Aplikasi AI", "Aplikasi AI"),
    "AI Assistant": ("Asisten AI", "Pembantu AI"),
    "AI Compliance Check": ("Pemeriksaan Kepatuhan AI", "Semakan Pematuhan AI"),
    "AI Generate": ("Buat dengan AI", "Jana dengan AI"),
    "AI Generate Doc": ("Buat Dokumen AI", "Jana Dokumen AI"),
    "AI Generating...": ("AI sedang membuat...", "AI sedang menjana..."),
    "AI Spreadsheet Translation": ("Terjemahan Spreadsheet AI", "Terjemahan Hamparan AI"),
    "AI Suggested Mapping": ("Pemetaan Saran AI", "Pemetaan Cadangan AI"),
    "AI Translate": ("Terjemahan AI", "Terjemah AI"),
    "AI compliance summary": ("Ringkasan kepatuhan AI", "Ringkasan pematuhan AI"),
    "AI console": ("Konsol AI", "Konsol AI"),
    "AI content generation failed": ("Pembuatan konten AI gagal", "Penjanaan kandungan AI gagal"),
    "AI features panel coming soon.": ("Panel fitur AI segera hadir.", "Panel ciri AI akan datang."),
    "AI generate trade document": ("Buat dokumen perdagangan dengan AI", "Jana dokumen perdagangan dengan AI"),
    "AI generating...": ("AI sedang membuat...", "AI sedang menjana..."),
    "AI generation failed": ("Pembuatan AI gagal", "Penjanaan AI gagal"),
    "AI generation failed. Try a more detailed description.": (
        "Pembuatan AI gagal. Coba deskripsi yang lebih detail.",
        "Penjanaan AI gagal. Cuba penerangan yang lebih terperinci.",
    ),
    "AI import content": ("Impor konten AI", "Import kandungan AI"),
    "AI import product": ("Impor produk AI", "Import produk AI"),
    "AI quotation draft": ("Draf penawaran AI", "Draf sebut harga AI"),
    "AI revision applied": ("Revisi AI diterapkan", "Semakan AI digunakan"),
    "AI revision failed — try rephrasing": ("Revisi AI gagal — coba ubah frasa", "Semakan AI gagal — cuba ubah ayat"),
    "AI revision failed — try rephrasing your instruction": (
        "Revisi AI gagal — coba ubah instruksi Anda",
        "Semakan AI gagal — cuba ubah arahan anda",
    ),
    "AI summary of inquiry compliance/risk flags when configured.": (
        "Ringkasan AI flag kepatuhan/risiko permintaan jika dikonfigurasi.",
        "Ringkasan AI bendera pematuhan/risiko pertanyaan jika dikonfigurasi.",
    ),
    "For sales reference only — not a substitute for legal/compliance review.": (
        "Hanya untuk referensi penjualan — bukan pengganti tinjauan hukum/kepatuhan.",
        "Untuk rujukan jualan sahaja — bukan pengganti semakan undang-undang/pematuhan.",
    ),
    "AI targeted revision": ("Revisi AI tertarget", "Semakan AI disasarkan"),
    "AI thinking...": ("AI sedang berpikir...", "AI sedang berfikir..."),
    "AI translate content": ("Terjemahkan konten AI", "Terjemah kandungan AI"),
    "AI-powered product recommendations, compliance checks, and intelligent search.": (
        "Rekomendasi produk, pemeriksaan kepatuhan, dan pencarian cerdas berbasis AI.",
        "Cadangan produk, semakan pematuhan, dan carian pintar berasaskan AI.",
    ),
    "Abbreviation": ("Singkatan", "Singkatan"),
    "Accept": ("Terima", "Terima"),
    "Accepted": ("Diterima", "Diterima"),
    "Account Status": ("Status Akun", "Status Akaun"),
    "Accounts Receivable": ("Piutang Usaha", "Akaun Belum Terima"),
    "Accounts receivable, payment tracking, and revenue analytics.": (
        "Piutang usaha, pelacakan pembayaran, dan analitik pendapatan.",
        "Akaun belum terima, penjejakan pembayaran, dan analitik hasil.",
    ),
    "Action": ("Aksi", "Tindakan"),
    "Activity": ("Aktivitas", "Aktiviti"),
    "Activity Log": ("Log Aktivitas", "Log Aktiviti"),
    "Actual Delivery": ("Pengiriman Aktual", "Penghantaran Sebenar"),
    "Add": ("Tambah", "Tambah"),
    "Additives (E-numbers)": ("Aditif (nomor E)", "Aditif (nombor E)"),
    "Admin": ("Admin", "Admin"),
    "After": ("Sesudah", "Selepas"),
    "After uploading an inventory/product Excel file, AI suggests column → field mappings.\nReview the blue banner and adjust mappings below before confirming import.": (
        "Setelah mengunggah file Excel inventaris/produk, AI menyarankan pemetaan kolom → field.\nTinjau banner biru dan sesuaikan pemetaan di bawah sebelum mengonfirmasi impor.",
        "Selepas muat naik fail Excel inventori/produk, AI mencadangkan pemetaan lajur → medan.\nSemak banner biru dan laraskan pemetaan di bawah sebelum mengesahkan import.",
    ),
    "Agent Mode": ("Mode Agen", "Mod Ejen"),
    "Alias": ("Alias", "Alias"),
    "Approval Threshold": ("Ambang Persetujuan", "Ambang Kelulusan"),
    "Arabic": ("Arab", "Arab"),
    "Article translated and published": ("Artikel diterjemahkan dan diterbitkan", "Artikel diterjemah dan diterbitkan"),
    "Author": ("Penulis", "Pengarang"),
    "Author Avatar URL": ("URL Avatar Penulis", "URL Avatar Pengarang"),
    "Author Bio": ("Bio Penulis", "Bio Pengarang"),
    "Auto detect": ("Deteksi otomatis", "Kesan automatik"),
    "B2B Coordinator": ("Koordinator B2B", "Penyelaras B2B"),
    "B2B org credit limits and approval tiers.": (
        "Batas kredit organisasi B2B dan tingkat persetujuan.",
        "Had kredit organisasi B2B dan peringkat kelulusan.",
    ),
    "Badge URL": ("URL Lencana", "URL Lencana"),
    "Basic Information": ("Informasi Dasar", "Maklumat Asas"),
    "Batch Number": ("Nomor Batch", "Nombor Kelompok"),
    "Before": ("Sebelum", "Sebelum"),
    "Bill To": ("Tagihan Kepada", "Bil Kepada"),
    "Bill of Lading": ("Bill of Lading", "Bill of Lading"),
    "Blog Posts": ("Artikel Blog", "Catatan Blog"),
    "Body": ("Isi", "Badan"),
    "Both parties confirmed": ("Kedua pihak mengonfirmasi", "Kedua-dua pihak mengesahkan"),
    "Business License": ("Izin Usaha", "Lesen Perniagaan"),
    "Business intelligence dashboards with revenue, order, and conversion metrics.": (
        "Dasbor intelijen bisnis dengan metrik pendapatan, pesanan, dan konversi.",
        "Papan pemuka inteligen perniagaan dengan metrik hasil, pesanan, dan penukaran.",
    ),
    "Buyer": ("Pembeli", "Pembeli"),
    "By": ("Oleh", "Oleh"),
    "COGS": ("COGS", "COGS"),
    "CREDIT NOTE": ("NOTA KREDIT", "NOTA KREDIT"),
    "CandyPro Admin": ("CandyPro Admin", "CandyPro Admin"),
    "Carbohydrates (g)": ("Karbohidrat (g)", "Karbohidrat (g)"),
    "Case Studies": ("Studi Kasus", "Kajian Kes"),
    "Certificate URL": ("URL Sertifikat", "URL Sijil"),
    "Certificate of Origin": ("Sertifikat Asal", "Sijil Asal Usul"),
    "Certification": ("Sertifikasi", "Pensijilan"),
    "Certification name is required.": ("Nama sertifikasi wajib diisi.", "Nama pensijilan diperlukan."),
    "Challenge": ("Tantangan", "Cabaran"),
    "Chat about this trade — documents, compliance, logistics.\nAgent may call trade tools; replies stream in the chat panel.\nUse AI Generate Document below for PI/CI/SC drafts.": (
        "Obrolan tentang perdagangan ini — dokumen, kepatuhan, logistik.\nAgen dapat memanggil alat perdagangan; balasan mengalir di panel obrolan.\nGunakan Buat Dokumen AI di bawah untuk draf PI/CI/SC.",
        "Sembang tentang perdagangan ini — dokumen, pematuhan, logistik.\nEjen boleh panggil alat perdagangan; balasan distrim dalam panel sembang.\nGunakan Jana Dokumen AI di bawah untuk draf PI/CI/SC.",
    ),
    "Chatbot (optional order)": ("Chatbot (pesanan opsional)", "Chatbot (pesanan pilihan)"),
    "Check inventory alerts": ("Periksa peringatan inventaris", "Semak amaran inventori"),
    "Chinese": ("Tionghoa", "Cina"),
    "Chinese category name is required": ("Nama kategori Tionghoa wajib diisi", "Nama kategori Cina diperlukan"),
    "Choose .xlsx file": ("Pilih file .xlsx", "Pilih fail .xlsx"),
    "Choose a product...": ("Pilih produk...", "Pilih produk..."),
    "City": ("Kota", "Bandar"),
    "Click or drag XLSX file here": ("Klik atau seret file XLSX ke sini", "Klik atau seret fail XLSX ke sini"),
    "Cocoa Solids %": ("Padatan Kakao %", "Pepejal Koko %"),
    "Column Mapping": ("Pemetaan Kolom", "Pemetaan Lajur"),
    "Comma-separated": ("Pisahkan dengan koma", "Pisahkan dengan koma"),
    "Compliance": ("Kepatuhan", "Pematuhan"),
    "Compliance Status": ("Status Kepatuhan", "Status Pematuhan"),
    "Compliance verified": ("Kepatuhan terverifikasi", "Pematuhan disahkan"),
    "Config (JSON)": ("Konfigurasi (JSON)", "Konfigurasi (JSON)"),
    "Configuration": ("Konfigurasi", "Konfigurasi"),
    "Configurations": ("Konfigurasi", "Konfigurasi"),
    "Configure platform settings and preferences.": (
        "Konfigurasi pengaturan dan preferensi platform.",
        "Konfigurasi tetapan dan keutamaan platform.",
    ),
    "Consignee": ("Penerima", "Penerima"),
    "Contact Person": ("Kontak Person", "Orang Hubungan"),
    "Context": ("Konteks", "Konteks"),
    "Contract": ("Kontrak", "Kontrak"),
    "Convert this inquiry to an order for the customer.": (
        "Konversi permintaan ini menjadi pesanan untuk pelanggan.",
        "Tukar pertanyaan ini kepada pesanan untuk pelanggan.",
    ),
    "Convert to MD": ("Konversi ke MD", "Tukar ke MD"),
    "Converted": ("Dikonversi", "Ditukar"),
    "Converting...": ("Mengonversi...", "Menukar..."),
    "Correction": ("Koreksi", "Pembetulan"),
    "Counter-offers and price negotiation with the buyer.": (
        "Penawaran balik dan negosiasi harga dengan pembeli.",
        "Tawaran balas dan rundingan harga dengan pembeli.",
    ),
    "Creating...": ("Membuat...", "Mencipta..."),
    "Ctrl+K inline edit": ("Edit inline Ctrl+K", "Edit sebaris Ctrl+K"),
    "Current Packaging Specs": ("Spesifikasi Kemasan Saat Ini", "Spesifikasi Pembungkusan Semasa"),
    "Current Stock": ("Stok Saat Ini", "Stok Semasa"),
    "Damage/Loss": ("Kerusakan/Kehilangan", "Kerosakan/Kehilangan"),
    "Danger Zone": ("Zona Bahaya", "Zon Bahaya"),
    "Days": ("Hari", "Hari"),
    "Deliveries": ("Pengiriman", "Penghantaran"),
    "Delivery": ("Pengiriman", "Penghantaran"),
    "Delivery Terms": ("Syarat Pengiriman", "Terma Penghantaran"),
    "Delivery confirmed.": ("Pengiriman dikonfirmasi.", "Penghantaran disahkan."),
    "Describe how to change the selection…": ("Jelaskan cara mengubah pilihan…", "Terangkan cara menukar pilihan…"),
    "Describe the case study for AI to draft...": ("Jelaskan studi kasus untuk draf AI...", "Terangkan kajian kes untuk draf AI..."),
    "Describe the topic or key points (any language). AI will draft in Chinese first...": (
        "Jelaskan topik atau poin utama (bahasa apa pun). AI akan membuat draf Tionghoa terlebih dahulu...",
        "Terangkan topik atau perkara utama (sebarang bahasa). AI akan draf Cina dahulu...",
    ),
    "Describe your product": ("Jelaskan produk Anda", "Terangkan produk anda"),
    "Dietary Labels": ("Label Diet", "Label Diet"),
    "Dimensions": ("Dimensi", "Dimensi"),
    "Dismiss": ("Tutup", "Abaikan"),
    "Distributor": ("Distributor", "Pengedar"),
    "Document generated successfully": ("Dokumen berhasil dibuat", "Dokumen berjaya dijana"),
    "Documents": ("Dokumen", "Dokumen"),
    "Download Excel reports. Monetary columns use the selected currency.": (
        "Unduh laporan Excel. Kolom moneter menggunakan mata uang yang dipilih.",
        "Muat turun laporan Excel. Lajur monetari menggunakan mata wang yang dipilih.",
    ),
    "Download Template": ("Unduh Template", "Muat Turun Templat"),
    "Download started": ("Unduhan dimulai", "Muat turun bermula"),
    "ETA": ("ETA", "ETA"),
    "Edit": ("Edit", "Edit"),
    "Edit Certification": ("Edit Sertifikasi", "Edit Pensijilan"),
    "Edit Flow": ("Edit Alur", "Edit Aliran"),
    "Edit Inquiry": ("Edit Permintaan", "Edit Pertanyaan"),
    "Edit Solution": ("Edit Solusi", "Edit Penyelesaian"),
    "Edit selection": ("Edit pilihan", "Edit pilihan"),
    "Editing {count} products": ("Mengedit {count} produk", "Mengedit {count} produk"),
    "Email": ("Email", "E-mel"),
    "Email address": ("Alamat email", "Alamat e-mel"),
    "Energy (kJ)": ("Energi (kJ)", "Tenaga (kJ)"),
    "Energy (kcal)": ("Energi (kcal)", "Tenaga (kcal)"),
    "English": ("Inggris", "Inggeris"),
    "Enter a product description on the left and click Generate to see AI-filled fields here.": (
        "Masukkan deskripsi produk di kiri dan klik Buat untuk melihat field yang diisi AI di sini.",
        "Masukkan penerangan produk di kiri dan klik Jana untuk lihat medan diisi AI di sini.",
    ),
    "Enter a topic for AI to write about...": ("Masukkan topik untuk AI tulis...", "Masukkan topik untuk AI tulis..."),
    'Enter after sales verification for catalog display. You may state a specific reference (e.g. "25 business days after order confirmation") — do not use vague promises like "approx. X weeks". Leave blank or use "confirmed at order time" until verified.': (
        'Isi setelah verifikasi penjualan untuk tampilan katalog. Anda dapat menyebut referensi spesifik (mis. "25 hari kerja setelah konfirmasi pesanan") — jangan gunakan janji samar seperti "sekitar X minggu". Kosongkan atau gunakan "dikonfirmasi saat pesanan" hingga terverifikasi.',
        'Isi selepas pengesahan jualan untuk paparan katalog. Anda boleh nyatakan rujukan khusus (cth. "25 hari bekerja selepas pengesahan pesanan") — jangan guna janji kabur seperti "anggaran X minggu". Biarkan kosong atau guna "disahkan semasa pesanan" sehingga disahkan.',
    ),
    "Enter context for AI document generation...": ("Masukkan konteks untuk pembuatan dokumen AI...", "Masukkan konteks untuk penjanaan dokumen AI..."),
    "Entity ID": ("ID Entitas", "ID Entiti"),
    "Estimated Delivery": ("Perkiraan Pengiriman", "Anggaran Penghantaran"),
    "Event": ("Acara", "Acara"),
    "Event Hooks": ("Hook Acara", "Hook Acara"),
    "Events": ("Acara", "Acara"),
    "Excerpt": ("Kutipan", "Petikan"),
    "Executions": ("Eksekusi", "Pelaksanaan"),
    "Expected Delivery": ("Pengiriman Diharapkan", "Penghantaran Dijangka"),
    "Fat (g)": ("Lemak (g)", "Lemak (g)"),
    "Fiber (g)": ("Serat (g)", "Serat (g)"),
    "Field": ("Field", "Medan"),
    "Filter": ("Filter", "Tapis"),
    "Filter Status": ("Filter Status", "Tapis Status"),
    "Flavor": ("Rasa", "Perisa"),
    "Flavor Requirements": ("Persyaratan Rasa", "Keperluan Perisa"),
    "Flavors (comma separated)": ("Rasa (pisahkan koma)", "Perisa (pisahkan koma)"),
    "Flows": ("Alur", "Aliran"),
    "Formulation": ("Formulasi", "Formulasi"),
    "Freight Terms": ("Syarat Pengangkutan", "Terma Pengangkutan"),
    "Frequency": ("Frekuensi", "Kekerapan"),
    "From": ("Dari", "Dari"),
    "Fulfillment": ("Pemenuhan", "Pemenuhan"),
    "Fulfillment created.": ("Pemenuhan dibuat.", "Pemenuhan dicipta."),
    "Full OEM": ("OEM Penuh", "OEM Penuh"),
    "Full name": ("Nama lengkap", "Nama penuh"),
    "GMO": ("GMO", "GMO"),
    "GMO Status": ("Status GMO", "Status GMO"),
    "GMO-Free Certified": ("Bersertifikat Bebas GMO", "Bersijil Bebas GMO"),
    "GTIN / Barcode": ("GTIN / Barcode", "GTIN / Barcode"),
    "Generate": ("Buat", "Jana"),
    "Generate Quotation": ("Buat Penawaran", "Jana Sebut Harga"),
    "Generate a {type} for this trade transaction.": ("Buat {type} untuk transaksi perdagangan ini.", "Jana {type} untuk transaksi perdagangan ini."),
    "Generate edit": ("Buat edit", "Jana suntingan"),
    "Generate {type}": ("Buat {type}", "Jana {type}"),
    "Generating product data...": ("Membuat data produk...", "Menjana data produk..."),
    "Generating...": ("Membuat...", "Menjana..."),
    "Gluten-Free": ("Bebas Gluten", "Bebas Gluten"),
    "Got it": ("Mengerti", "Faham"),
    "Gross Weight (kg)": ("Berat Kotor (kg)", "Berat Kasar (kg)"),
    "Gross Weight/Carton (kg)": ("Berat Kotor/Karton (kg)", "Berat Kasar/Karton (kg)"),
    "Group": ("Grup", "Kumpulan"),
    "HTTP": ("HTTP", "HTTP"),
    "Halal": ("Halal", "Halal"),
    "Halal Certified": ("Bersertifikat Halal", "Bersijil Halal"),
    "Health Certificate": ("Sertifikat Kesehatan", "Sijil Kesihatan"),
    "Height (mm)": ("Tinggi (mm)", "Tinggi (mm)"),
    "Hook ID": ("ID Hook", "ID Hook"),
    "Hooks": ("Hook", "Hook"),
    "How to use AI": ("Cara menggunakan AI", "Cara menggunakan AI"),
    "ID": ("ID", "ID"),
    "INVOICE": ("FAKTUR", "INVOIS"),
    "Icon": ("Ikon", "Ikon"),
    "Image URLs detected - will be auto-uploaded on import": (
        "URL gambar terdeteksi - akan diunggah otomatis saat impor",
        "URL imej dikesan - akan dimuat naik automatik semasa import",
    ),
    "Images (comma separated URLs)": ("Gambar (URL pisahkan koma)", "Imej (URL pisahkan koma)"),
    "Images (comma separated)": ("Gambar (pisahkan koma)", "Imej (pisahkan koma)"),
    "Incoterms": ("Incoterms", "Incoterms"),
    "Indonesian": ("Indonesia", "Indonesia"),
    "Industry": ("Industri", "Industri"),
    "Ingredient Compliance": ("Kepatuhan Bahan", "Pematuhan Bahan"),
    "Initial": ("Awal", "Permulaan"),
    "Inner Pack Config": ("Konfigurasi Kemasan Dalam", "Konfigurasi Pembungkusan Dalam"),
    "Inquiry": ("Permintaan", "Pertanyaan"),
    "Inquiry Conversion": ("Konversi Permintaan", "Penukaran Pertanyaan"),
    "Inquiry ID": ("ID Permintaan", "ID Pertanyaan"),
    "Inspection Result": ("Hasil Inspeksi", "Keputusan Pemeriksaan"),
    "Invalid JSON config.": ("Konfigurasi JSON tidak valid.", "Konfigurasi JSON tidak sah."),
    "Issuer": ("Penerbit", "Pengeluar"),
    "Issuing Authority": ("Otoritas Penerbit", "Pihak Berkuasa Pengeluar"),
    "Japanese": ("Jepang", "Jepun"),
    "KYB Status": ("Status KYB", "Status KYB"),
    "Key": ("Kunci", "Kunci"),
    "Korean": ("Korea", "Korea"),
    "Kosher": ("Kosher", "Kosher"),
    "Label Template ID": ("ID Template Label", "ID Templat Label"),
    "Labor": ("Tenaga Kerja", "Buruh"),
    "Last Login": ("Login Terakhir", "Log Masuk Terakhir"),
    "Leave empty to use default author bio": ("Kosongkan untuk bio penulis default", "Biarkan kosong untuk bio pengarang lalai"),
    "Leave empty to use default author name": ("Kosongkan untuk nama penulis default", "Biarkan kosong untuk nama pengarang lalai"),
    "Leave empty to use default author title": ("Kosongkan untuk jabatan penulis default", "Biarkan kosong untuk jawatan pengarang lalai"),
    "Leave empty to use default content": ("Kosongkan untuk konten default", "Biarkan kosong untuk kandungan lalai"),
    "Leave empty to use default excerpt": ("Kosongkan untuk kutipan default", "Biarkan kosong untuk petikan lalai"),
    "Leave empty to use default name": ("Kosongkan untuk nama default", "Biarkan kosong untuk nama lalai"),
    "Leave empty to use default title": ("Kosongkan untuk judul default", "Biarkan kosong untuk tajuk lalai"),
    "Length (mm)": ("Panjang (mm)", "Panjang (mm)"),
    "Load": ("Muat", "Muat"),
    "Locale": ("Locale", "Locale"),
    "Location": ("Lokasi", "Lokasi"),
    "Logistics": ("Logistik", "Logistik"),
    "MOQ": ("MOQ", "MOQ"),
    "Malay": ("Melayu", "Melayu"),
    "Manual compliance ack": ("Konfirmasi kepatuhan manual", "Pengesahan pematuhan manual"),
    "Marked as shipped.": ("Ditandai sebagai dikirim.", "Ditanda sebagai dihantar."),
    "Market Profile": ("Profil Pasar", "Profil Pasaran"),
    "Market profile saved.": ("Profil pasar disimpan.", "Profil pasaran disimpan."),
    "Marketplace": ("Marketplace", "Pasaran"),
    "Material": ("Material", "Bahan"),
    "May Contain": ("Mungkin Mengandung", "Mungkin Mengandungi"),
    "Measurement (CBM)": ("Pengukuran (CBM)", "Pengukuran (CBM)"),
    "Members": ("Anggota", "Ahli"),
    "Message": ("Pesan", "Mesej"),
    "Method": ("Metode", "Kaedah"),
    "Milk Solids %": ("Padatan Susu %", "Pepejal Susu %"),
    "Min Qty": ("Jml Min.", "Ktl Min."),
    "Modal AI generate": ("Modal buat AI", "Modal jana AI"),
    "Model": ("Model", "Model"),
    "Monetary": ("Moneter", "Monetari"),
    "Month": ("Bulan", "Bulan"),
    "Months": ("Bulan", "Bulan"),
    "Multiple languages": ("Beberapa bahasa", "Pelbagai bahasa"),
    "Negotiation": ("Negosiasi", "Rundingan"),
    "Net Weight/Pack (g)": ("Berat Bersih/Kemasan (g)", "Berat Bersih/Pek (g)"),
    "Net Weight/Piece (g)": ("Berat Bersih/Buah (g)", "Berat Bersih/Keping (g)"),
    "Never": ("Tidak pernah", "Tidak pernah"),
    "Non-GMO": ("Non-GMO", "Non-GMO"),
    "Nutrition (per 100g)": ("Nutrisi (per 100g)", "Nutrisi (setiap 100g)"),
    "OEM": ("OEM", "OEM"),
    "OEM Available": ("OEM Tersedia", "OEM Tersedia"),
    "OEM Needed": ("Butuh OEM", "Perlu OEM"),
    "OG Image (Social Share)": ("Gambar OG (Berbagi Sosial)", "Imej OG (Kongsi Sosial)"),
    "Offer": ("Penawaran", "Tawaran"),
    "Offer accepted.": ("Penawaran diterima.", "Tawaran diterima."),
    "Offer rejected.": ("Penawaran ditolak.", "Tawaran ditolak."),
    "Optional. 1200×630 recommended for social previews.": (
        "Opsional. 1200×630 disarankan untuk pratinjau sosial.",
        "Pilihan. 1200×630 disyorkan untuk pratonton sosial.",
    ),
    "Optional. Overrides thumbnail for Facebook/LinkedIn previews. 1200×630 recommended.": (
        "Opsional. Mengganti thumbnail untuk pratinjau Facebook/LinkedIn. 1200×630 disarankan.",
        "Pilihan. Ganti thumbnail untuk pratonton Facebook/LinkedIn. 1200×630 disyorkan.",
    ),
    "Organic": ("Organik", "Organik"),
    "Organization": ("Organisasi", "Organisasi"),
    "Other": ("Lainnya", "Lain"),
    "Outbound event notifications.": ("Notifikasi acara keluar.", "Pemberitahuan acara keluar."),
    "PI Reference": ("Referensi PI", "Rujukan PI"),
    "PROFORMA INVOICE": ("FAKTUR PROFORMA", "INVOIS PROFORMA"),
    "Packaging": ("Kemasan", "Pembungkusan"),
    "Packaging Requirements": ("Persyaratan Kemasan", "Keperluan Pembungkusan"),
    "Packaging Size": ("Ukuran Kemasan", "Saiz Pembungkusan"),
    "Packaging Weight (g)": ("Berat Kemasan (g)", "Berat Pembungkusan (g)"),
    "Packing List": ("Daftar Kemasan", "Senarai Pembungkusan"),
    "Packs/Carton": ("Kemasan/Karton", "Pek/Karton"),
    "Pallet Config": ("Konfigurasi Palet", "Konfigurasi Palet"),
    "Parsing file...": ("Mengurai file...", "Menghuraikan fail..."),
    "Passed": ("Lulus", "Lulus"),
    "Password": ("Kata sandi", "Kata laluan"),
    "Payload": ("Payload", "Payload"),
    "Payment": ("Pembayaran", "Pembayaran"),
    "Payment Breakdown": ("Rincian Pembayaran", "Pecahan Pembayaran"),
    "Payment confirmed": ("Pembayaran dikonfirmasi", "Pembayaran disahkan"),
    "Payment created": ("Pembayaran dibuat", "Pembayaran dicipta"),
    "Payment must be confirmed (paid or partial) before moving to execution stages (confirmed, production, shipped, delivered).": (
        "Pembayaran harus dikonfirmasi (lunas atau sebagian) sebelum pindah ke tahap eksekusi (dikonfirmasi, produksi, dikirim, diterima).",
        "Pembayaran mesti disahkan (dibayar atau separa) sebelum beralih ke peringkat pelaksanaan (disahkan, pengeluaran, dihantar, diterima).",
    ),
    "Payment refunded": ("Pembayaran direfund", "Pembayaran dibayar balik"),
    "Personal details and current status.": ("Detail pribadi dan status saat ini.", "Butiran peribadi dan status semasa."),
    "Pick document type (PI, CI, SC, etc.) and optional context.\nAI drafts from current trade data and saves to the system.\nAlways verify fields in the document list before sending to customers.": (
        "Pilih tipe dokumen (PI, CI, SC, dll.) dan konteks opsional.\nAI membuat draf dari data perdagangan saat ini dan menyimpan ke sistem.\nSelalu verifikasi field di daftar dokumen sebelum kirim ke pelanggan.",
        "Pilih jenis dokumen (PI, CI, SC, dll.) dan konteks pilihan.\nAI draf dari data perdagangan semasa dan simpan ke sistem.\nSentiasa sahkan medan dalam senarai dokumen sebelum hantar kepada pelanggan.",
    ),
    "Pieces/Pack": ("Buah/Kemasan", "Keping/Pek"),
    "Placed on": ("Ditempatkan pada", "Diletakkan pada"),
    "Plan-Execute-Replan": ("Rencana-Eksekusi-Rencana Ulang", "Rancang-Laksana-Rancang Semula"),
    "Please select a .xlsx file": ("Silakan pilih file .xlsx", "Sila pilih fail .xlsx"),
    "Please select an XLSX file": ("Silakan pilih file XLSX", "Sila pilih fail XLSX"),
    "Plugin and internal hook configurations.": ("Konfigurasi plugin dan hook internal.", "Konfigurasi plugin dan hook dalaman."),
    "Port of Discharge": ("Pelabuhan Bongkar", "Pelabuhan Pelepasan"),
    "Preview": ("Pratinjau", "Pratonton"),
    "Primary Packaging": ("Kemasan Primer", "Pembungkusan Utama"),
    "Priority": ("Prioritas", "Keutamaan"),
    "Project": ("Proyek", "Projek"),
    "Projects": ("Proyek", "Projek"),
    "Protein (g)": ("Protein (g)", "Protein (g)"),
    "Qty": ("Jml", "Ktl"),
    "Quality Standard": ("Standar Kualitas", "Piawaian Kualiti"),
    "Quick Document Generation": ("Pembuatan Dokumen Cepat", "Penjanaan Dokumen Pantas"),
    "Quick ODM": ("ODM Cepat", "ODM Pantas"),
    "Quotation": ("Penawaran", "Sebut Harga"),
    "Quote": ("Penawaran", "Sebut Harga"),
    "Quoted amount": ("Jumlah penawaran", "Jumlah sebut harga"),
    "Quoted amount must be greater than 0.": ("Jumlah penawaran harus lebih dari 0.", "Jumlah sebut harga mesti lebih daripada 0."),
    "RFM Analysis": ("Analisis RFM", "Analisis RFM"),
    "Read Time (min)": ("Waktu Baca (menit)", "Masa Baca (min)"),
    "Receive": ("Terima", "Terima"),
    "Received": ("Diterima", "Diterima"),
    "Recency": ("Keterkinian", "Kebaruan"),
    "Recommend pricing for candy products": ("Rekomendasikan harga untuk produk permen", "Cadangkan harga untuk produk gula-gula"),
    "Reference transit estimate for internal quoting. Subject to change; confirm at order time.": (
        "Perkiraan transit referensi untuk penawaran internal. Dapat berubah; konfirmasi saat pesanan.",
        "Anggaran transit rujukan untuk sebut harga dalaman. Boleh berubah; sahkan semasa pesanan.",
    ),
    "Regenerate": ("Buat ulang", "Jana semula"),
    "Registration Number": ("Nomor Registrasi", "Nombor Pendaftaran"),
    "Reload": ("Muat ulang", "Muat semula"),
    "Reorder Qty": ("Jml Pemesanan Ulang", "Ktl Pesanan Semula"),
    "Replenishment": ("Pengisian Ulang", "Penambahan Stok"),
    "Requested": ("Diminta", "Diminta"),
    "Required Cert Keywords": ("Kata Kunci Sertifikasi Wajib", "Kata Kunci Sijil Diperlukan"),
    "Requirement": ("Persyaratan", "Keperluan"),
    "Requirements": ("Persyaratan", "Keperluan"),
    "Restock": ("Restok", "Stok Semula"),
    "Result": ("Hasil", "Keputusan"),
    "Return ID": ("ID Retur", "ID Pemulangan"),
    "Return approved.": ("Retur disetujui.", "Pemulangan diluluskan."),
    "Return received.": ("Retur diterima.", "Pemulangan diterima."),
    "Return rejected.": ("Retur ditolak.", "Pemulangan ditolak."),
    "Review and edit the Chinese draft below. On publish, all locales will be translated and synced to the public blog.": (
        "Tinjau dan edit draf Tionghoa di bawah. Saat diterbitkan, semua locale akan diterjemahkan dan disinkronkan ke blog publik.",
        "Semak dan sunting draf Cina di bawah. Semasa diterbitkan, semua locale akan diterjemah dan disegerakkan ke blog awam.",
    ),
    "Review and process customer return requests.": (
        "Tinjau dan proses permintaan retur pelanggan.",
        "Semak dan proses permintaan pemulangan pelanggan.",
    ),
    "Reviewed By": ("Ditinjau Oleh", "Disemak Oleh"),
    "Revising…": ("Merevisi…", "Menyemak…"),
    "Revision scope": ("Cakupan revisi", "Skop semakan"),
    "Risk": ("Risiko", "Risiko"),
    "Role": ("Peran", "Peranan"),
    "SKU": ("SKU", "SKU"),
    "Sales Contract": ("Kontrak Penjualan", "Kontrak Jualan"),
    "Sales Velocity": ("Kecepatan Penjualan", "Kelajuan Jualan"),
    "Salt (g)": ("Garam (g)", "Garam (g)"),
    "Sample ID": ("ID Sampel", "ID Sampel"),
    "Sample MOQ": ("MOQ Sampel", "MOQ Sampel"),
    "Sample Specs": ("Spesifikasi Sampel", "Spesifikasi Sampel"),
    'Sample lead time reference — confirmed by sales in the sample quote; do not use "approx. X weeks".': (
        'Referensi waktu pengiriman sampel — dikonfirmasi penjualan dalam penawaran sampel; jangan gunakan "sekitar X minggu".',
        'Rujukan masa penghantaran sampel — disahkan jualan dalam sebut harga sampel; jangan guna "anggaran X minggu".',
    ),
    "Samples": ("Sampel", "Sampel"),
    "Sampling": ("Pengambilan Sampel", "Pensampelan"),
    "Saturated Fat (g)": ("Lemak Jenuh (g)", "Lemak Tepu (g)"),
    "Secret (save now)": ("Rahasia (simpan sekarang)", "Rahsia (simpan sekarang)"),
    "Segment": ("Segmen", "Segmen"),
    "Self-fulfill": ("Pemenuhan sendiri", "Pemenuhan sendiri"),
    "Services (comma separated)": ("Layanan (pisahkan koma)", "Perkhidmatan (pisahkan koma)"),
    "Set To": ("Atur Ke", "Tetapkan Ke"),
    "Settlements": ("Penyelesaian", "Penyelesaian"),
    "Shape": ("Bentuk", "Bentuk"),
    "Shapes (comma separated)": ("Bentuk (pisahkan koma)", "Bentuk (pisahkan koma)"),
    "Ship": ("Kirim", "Hantar"),
    "Shipper": ("Pengirim", "Penghantar"),
    "Show me top selling products": ("Tampilkan produk terlaris", "Tunjukkan produk terlaris"),
    "Single language": ("Satu bahasa", "Satu bahasa"),
    "Slug": ("Slug", "Slug"),
    "Slug is required": ("Slug wajib diisi", "Slug diperlukan"),
    "Solution": ("Solusi", "Penyelesaian"),
    "Solutions": ("Solusi", "Penyelesaian"),
    "Source Language": ("Bahasa Sumber", "Bahasa Sumber"),
    "Source language (optional)": ("Bahasa sumber (opsional)", "Bahasa sumber (pilihan)"),
    "Special Terms": ("Syarat Khusus", "Terma Khas"),
    "Specifications": ("Spesifikasi", "Spesifikasi"),
    "Specifications confirmed": ("Spesifikasi dikonfirmasi", "Spesifikasi disahkan"),
    "Standard": ("Standar", "Standard"),
    "Start a conversation with the AI Agent": ("Mulai percakapan dengan Agen AI", "Mulakan perbualan dengan Ejen AI"),
    "Start writing...": ("Mulai menulis...", "Mula menulis..."),
    "State": ("Provinsi", "Negeri"),
    "State / Province": ("Provinsi / Negara Bagian", "Negeri / Wilayah"),
    "Status": ("Status", "Status"),
    "Status Change": ("Perubahan Status", "Perubahan Status"),
    "Status...": ("Status...", "Status..."),
    "Step Tracker": ("Pelacak Langkah", "Penjejak Langkah"),
    "Steps": ("Langkah", "Langkah"),
    "Stock": ("Stok", "Stok"),
    "Stop": ("Berhenti", "Hentikan"),
    "Stream interrupted": ("Stream terputus", "Strim terganggu"),
    "Street": ("Jalan", "Jalan"),
    "Structured product references for compliance checks and quoting": (
        "Referensi produk terstruktur untuk pemeriksaan kepatuhan dan penawaran",
        "Rujukan produk berstruktur untuk semakan pematuhan dan sebut harga",
    ),
    "Submit Quote": ("Kirim Penawaran", "Hantar Sebut Harga"),
    "Submitted on": ("Dikirim pada", "Dihantar pada"),
    "Submitting...": ("Mengirim...", "Menghantar..."),
    "Subtotal": ("Subtotal", "Subjumlah"),
    "Subtract": ("Kurangi", "Tolak"),
    "Sugar-Free": ("Bebas Gula", "Bebas Gula"),
    "Sugars (g)": ("Gula (g)", "Gula (g)"),
    "Super Admin": ("Super Admin", "Super Admin"),
    "Superadmin": ("Superadmin", "Superadmin"),
    "Suspended": ("Ditangguhkan", "Digantung"),
    "TAX INVOICE": ("FAKTUR PAJAK", "INVOIS CUKAI"),
    "Tags (comma separated)": ("Tag (pisahkan koma)", "Tag (pisahkan koma)"),
    "Target Market": ("Pasar Target", "Pasaran Sasaran"),
    "Target language": ("Bahasa target", "Bahasa sasaran"),
    "Target languages": ("Bahasa target", "Bahasa sasaran"),
    "Temperature": ("Temperatur", "Suhu"),
    "Terms": ("Syarat", "Terma"),
    "Thai": ("Thailand", "Thai"),
    "Thumbnail": ("Thumbnail", "Thumbnail"),
    "Thumbnail URL": ("URL Thumbnail", "URL Thumbnail"),
    "Time": ("Waktu", "Masa"),
    "Timeline": ("Linimasa", "Garis Masa"),
    "To": ("Ke", "Ke"),
    "Tools Called": ("Alat Dipanggil", "Alat Dipanggil"),
    "Total": ("Total", "Jumlah"),
    "Total Gross Weight (kg)": ("Total Berat Kotor (kg)", "Jumlah Berat Kasar (kg)"),
    "Total Net Weight (kg)": ("Total Berat Bersih (kg)", "Jumlah Berat Bersih (kg)"),
    "Total Packages": ("Total Paket", "Jumlah Bungkusan"),
    "Total Volume (CBM)": ("Total Volume (CBM)", "Jumlah Isi Padu (CBM)"),
    "Total amount is required": ("Total jumlah wajib diisi", "Jumlah keseluruhan diperlukan"),
    "Track all system activity and changes across the platform.": (
        "Lacak semua aktivitas dan perubahan sistem di platform.",
        "Jejak semua aktiviti dan perubahan sistem merentasi platform.",
    ),
    "Trade": ("Perdagangan", "Perdagangan"),
    "Trade & Packaging": ("Perdagangan & Kemasan", "Perdagangan & Pembungkusan"),
    "Trade AI assistant": ("Asisten AI Perdagangan", "Pembantu AI Perdagangan"),
    "Trade Assistant": ("Asisten Perdagangan", "Pembantu Perdagangan"),
    "Trade ID": ("ID Perdagangan", "ID Perdagangan"),
    "Trade Transaction": ("Transaksi Perdagangan", "Transaksi Perdagangan"),
    "Trade status (optional)": ("Status perdagangan (opsional)", "Status perdagangan (pilihan)"),
    "Trade transactions": ("Transaksi perdagangan", "Transaksi perdagangan"),
    "Traditional Chinese": ("Tionghoa Tradisional", "Cina Tradisional"),
    "Transaction": ("Transaksi", "Transaksi"),
    "Transfer #": ("Transfer #", "Pemindahan #"),
    "Transfers": ("Transfer", "Pemindahan"),
    "Translate": ("Terjemahkan", "Terjemah"),
    "Translate & download": ("Terjemahkan & unduh", "Terjemah & muat turun"),
    "Translated file downloaded": ("File terjemahan diunduh", "Fail terjemahan dimuat turun"),
    "Translating & publishing...": ("Menerjemahkan & menerbitkan...", "Menterjemah & menerbitkan..."),
    "Translation completed on server; loaded latest translations from database": (
        "Terjemahan selesai di server; memuat terjemahan terbaru dari database",
        "Terjemahan selesai di pelayan; memuatkan terjemahan terkini dari pangkalan data",
    ),
    "Translation failed": ("Terjemahan gagal", "Terjemahan gagal"),
    "URL": ("URL", "URL"),
    "URL or upload": ("URL atau unggah", "URL atau muat naik"),
    "Upload Excel, choose single or batch translate mode.\nAI translates headers or selected column keys — useful for reports and term sheets.\nDownload the result; try a small sample before batch jobs.": (
        "Unggah Excel, pilih mode terjemahan tunggal atau batch.\nAI menerjemahkan header atau kunci kolom terpilih — berguna untuk laporan dan term sheet.\nUnduh hasilnya; coba sampel kecil sebelum batch.",
        "Muat naik Excel, pilih mod terjemah tunggal atau kelompok.\nAI menterjemah pengepala atau kunci lajur terpilih — berguna untuk laporan dan lembaran terma.\nMuat turun hasil; cuba sampel kecil sebelum kerja kelompok.",
    ),
    "Upload Image": ("Unggah Gambar", "Muat Naik Imej"),
    "Upload Images": ("Unggah Gambar", "Muat Naik Imej"),
    "Upload an .xlsx file; text cells are translated via Trade Agent (translate_content pipeline).": (
        "Unggah file .xlsx; sel teks diterjemahkan via Trade Agent (pipeline translate_content).",
        "Muat naik fail .xlsx; sel teks diterjemah melalui Trade Agent (saluran translate_content).",
    ),
    "Use AI to assist with trade documents.": ("Gunakan AI untuk membantu dokumen perdagangan.", "Gunakan AI untuk bantu dokumen perdagangan."),
    "Used": ("Digunakan", "Digunakan"),
    "Valid Until": ("Berlaku Hingga", "Sah Sehingga"),
    "Vegan": ("Vegan", "Vegan"),
    "Velocity": ("Kecepatan", "Kelajuan"),
    "Verify": ("Verifikasi", "Sahkan"),
    "Vessel/Voyage": ("Kapal/Pelayaran", "Kapal/Pelayaran"),
    "Vietnamese": ("Vietnam", "Vietnam"),
    "Voided": ("Dibatalkan", "Dibatalkan"),
    "Waiting for customer": ("Menunggu pelanggan", "Menunggu pelanggan"),
    "Water Activity (aʷ)": ("Aktivitas Air (aʷ)", "Aktiviti Air (aʷ)"),
    "Webhooks": ("Webhook", "Webhook"),
    "Website": ("Situs web", "Laman web"),
    "Webstore": ("Toko web", "Kedai web"),
    "Weight & Measurement": ("Berat & Pengukuran", "Berat & Pengukuran"),
    "WhatsApp": ("WhatsApp", "WhatsApp"),
    "While editing content, enter a topic and click Generate with AI to fill title, body, etc. (Chinese draft, no auto-translate).\nUse AI Translate in the translations section for other locales after saving.": (
        "Saat mengedit konten, masukkan topik dan klik Buat dengan AI untuk mengisi judul, isi, dll. (draf Tionghoa, tanpa terjemahan otomatis).\nGunakan Terjemahan AI di bagian terjemahan untuk locale lain setelah menyimpan.",
        "Semasa menyunting kandungan, masukkan topik dan klik Jana dengan AI untuk isi tajuk, badan, dll. (draf Cina, tanpa terjemah automatik).\nGunakan Terjemah AI dalam bahagian terjemahan untuk locale lain selepas simpan.",
    ),
    "Width (mm)": ("Lebar (mm)", "Lebar (mm)"),
    "Write your brief in any language. AI outputs a Chinese draft for review first.": (
        "Tulis brief Anda dalam bahasa apa pun. AI menghasilkan draf Tionghoa untuk ditinjau terlebih dahulu.",
        "Tulis ringkasan anda dalam sebarang bahasa. AI keluarkan draf Cina untuk semakan dahulu.",
    ),
    "XLSX AI translate": ("Terjemahan AI XLSX", "Terjemah AI XLSX"),
    "You": ("Anda", "Anda"),
    "[Stream stopped]": ("[Stream dihentikan]", "[Strim dihentikan]"),
    "[Tool completed]": ("[Alat selesai]", "[Alat selesai]"),
    "e.g. 12 units per display box": ("mis. 12 unit per kotak display", "cth. 12 unit setiap kotak paparan"),
    "e.g. 48 cases/layer × 5 layers": ("mis. 48 kardus/lapisan × 5 lapisan", "cth. 48 kes/lapisan × 5 lapisan"),
    "e.g. Shorten the title; add EU compliance details in paragraph 2; use a more professional tone…": (
        "mis. Persingkat judul; tambahkan detail kepatuhan UE di paragraf 2; gunakan nada lebih profesional…",
        "cth. Pendekkan tajuk; tambah butiran pematuhan EU dalam perenggan 2; guna nada lebih profesional…",
    ),
    "e.g. errors.my_new_code": ("mis. errors.my_new_code", "cth. errors.my_new_code"),
    "e.g., 150g milk chocolate bar with almonds, vegan, 12-month shelf life, individually flow-wrapped, 24 pieces per display box, halal certified...": (
        "mis., batang cokelat susu 150g dengan almond, vegan, masa simpan 12 bulan, flow-wrap individual, 24 buah per kotak display, bersertifikat halal...",
        "cth., bar coklat susu 150g dengan badam, vegan, jangka hayat 12 bulan, flow-wrap individu, 24 keping setiap kotak paparan, bersijil halal...",
    ),
    "flow-wrap, foil, box, bag, jar": ("flow-wrap, foil, kotak, kantong, toples", "flow-wrap, foil, kotak, beg, balang"),
    "g": ("g", "g"),
    "inventory": ("inventaris", "inventori"),
    "invoices": ("faktur", "invois"),
    "just now": ("baru saja", "baru sahaja"),
    "pending": ("menunggu", "menunggu"),
    "shipments": ("pengiriman", "penghantaran"),
    "this week": ("minggu ini", "minggu ini"),
    "{count} days ago": ("{count} hari lalu", "{count} hari lalu"),
    "{count} hours ago": ("{count} jam lalu", "{count} jam lalu"),
    "{count} minutes ago": ("{count} menit lalu", "{count} minit lalu"),
    "{count} selected": ("{count} dipilih", "{count} dipilih"),
    "{deleted} deleted, {errors} errors": ("{deleted} dihapus, {errors} kesalahan", "{deleted} dipadam, {errors} ralat"),
    "{from} → {to}": ("{from} → {to}", "{from} → {to}"),
    "{total} total": ("{total} total", "{total} jumlah"),
    "Material": ("Bahan", "Bahan"),
    "Field": ("Bidang", "Medan"),
    "Filter Status": ("Filter Status", "Tapis Status"),
    "Subtotal": ("Subtotal", "Subjumlah"),
    "Total": ("Total", "Jumlah"),
    "Distributor": ("Distributor", "Pengedar"),
    "Marketplace": ("Marketplace", "Pasaran"),
    "Total Volume (CBM)": ("Total Volume (CBM)", "Jumlah Isi Padu (CBM)"),
    "AI summary of inquiry compliance/risk flags when configured.\nFor sales reference only — not a substitute for legal/compliance review.": (
        "Ringkasan AI flag kepatuhan/risiko permintaan jika dikonfigurasi.\nHanya untuk referensi penjualan — bukan pengganti tinjauan hukum/kepatuhan.",
        "Ringkasan AI bendera pematuhan/risiko pertanyaan jika dikonfigurasi.\nUntuk rujukan jualan sahaja — bukan pengganti semakan undang-undang/pematuhan.",
    ),
    "1. Enter a topic or brief (any language) on the left.\n2. Click Generate Chinese Draft for a zh-first article.\n3. Review and edit the draft on the right.\n4. Select text and press Ctrl+K (Mac: ⌘K) for inline AI edits.\n5. Click Confirm & Publish to translate all locales and publish to the public blog.": (
        "1. Masukkan topik atau ringkasan (bahasa apa pun) di kiri.\n2. Klik Buat Draf Tionghoa untuk artikel zh-first.\n3. Tinjau dan edit draf di kanan.\n4. Pilih teks dan tekan Ctrl+K (Mac: ⌘K) untuk edit inline AI.\n5. Klik Konfirmasi & Terbitkan untuk menerjemahkan semua locale dan menerbitkan ke blog publik.",
        "1. Masukkan topik atau ringkasan (sebarang bahasa) di kiri.\n2. Klik Jana Draf Cina untuk artikel zh-first.\n3. Semak dan sunting draf di kanan.\n4. Pilih teks dan tekan Ctrl+K (Mac: ⌘K) untuk suntingan sebaris AI.\n5. Klik Sahkan & Terbitkan untuk menterjemah semua locale dan terbitkan ke blog awam.",
    ),
    "1. Select text in title, excerpt, or body.\n2. Press Ctrl+K (Mac: ⌘K) to open the floating editor.\n3. Describe the change (e.g. add compliance details, shorten title).\n4. Preview before/after diff — Accept or Reject.\n5. Repeat until satisfied, then publish.": (
        "1. Pilih teks di judul, kutipan, atau isi.\n2. Tekan Ctrl+K (Mac: ⌘K) untuk buka editor mengambang.\n3. Jelaskan perubahan (mis. tambah detail kepatuhan, persingkat judul).\n4. Pratinjau diff sebelum/sesudah — Terima atau Tolak.\n5. Ulangi hingga puas, lalu terbitkan.",
        "1. Pilih teks dalam tajuk, petikan, atau badan.\n2. Tekan Ctrl+K (Mac: ⌘K) untuk buka editor terapung.\n3. Terangkan perubahan (cth. tambah butiran pematuhan, pendekkan tajuk).\n4. Pratonton diff sebelum/selepas — Terima atau Tolak.\n5. Ulangi sehingga puas, kemudian terbitkan.",
    ),
    "When editing saved content, click AI Translate under Translations.\nSource fields (usually Chinese) are translated to en/ko/ar/ja/th/vi/id/ms.\nReview each locale tab and save.": (
        "Saat mengedit konten tersimpan, klik Terjemahan AI di bawah Terjemahan.\nField sumber (biasanya Tionghoa) diterjemahkan ke en/ko/ar/ja/th/vi/id/ms.\nTinjau setiap tab locale dan simpan.",
        "Semasa menyunting kandungan disimpan, klik Terjemah AI di bawah Terjemahan.\nMedan sumber (biasanya Cina) diterjemah ke en/ko/ar/ja/th/vi/id/ms.\nSemak setiap tab locale dan simpan.",
    ),
    "1. Describe the product in natural language (specs, ingredients, packaging, certs).\n2. Choose input language and click Generate with AI.\n3. Review auto-filled fields on the right.\n4. Click Save Product.\nUse AI Translate for other locales after saving.": (
        "1. Jelaskan produk dalam bahasa alami (spesifikasi, bahan, kemasan, sertifikasi).\n2. Pilih bahasa input dan klik Buat dengan AI.\n3. Tinjau field terisi otomatis di kanan.\n4. Klik Simpan Produk.\nGunakan Terjemahan AI untuk locale lain setelah menyimpan.",
        "1. Terangkan produk dalam bahasa natural (spesifikasi, bahan, pembungkusan, sijil).\n2. Pilih bahasa input dan klik Jana dengan AI.\n3. Semak medan diisi automatik di kanan.\n4. Klik Simpan Produk.\nGunakan Terjemah AI untuk locale lain selepas simpan.",
    ),
    "When editing a product, click AI Translate under Translations.\nName, summary, description, ingredients, etc. are translated from the primary locale.\nReview locale tabs before saving.": (
        "Saat mengedit produk, klik Terjemahan AI di bawah Terjemahan.\nNama, ringkasan, deskripsi, bahan, dll. diterjemahkan dari locale utama.\nTinjau tab locale sebelum menyimpan.",
        "Semasa menyunting produk, klik Terjemah AI di bawah Terjemahan.\nNama, ringkasan, penerangan, bahan, dll. diterjemah dari locale utama.\nSemak tab locale sebelum simpan.",
    ),
    "Pick an Agent mode on the right, then chat:\n• Chatbot: Q&A; optional order context.\n• Plan-Execute-Replan / B2B Coordinator / Trade Assistant: streaming agents.\n• Recommend / Search / Translate / Analyze inquiry / Generate quotation: one-shot JSON.\nFor Chatbot, select an order in the sidebar to discuss that order.": (
        "Pilih mode Agen di kanan, lalu obrolan:\n• Chatbot: Tanya jawab; konteks pesanan opsional.\n• Plan-Execute-Replan / B2B Coordinator / Trade Assistant: agen streaming.\n• Rekomendasi / Cari / Terjemahkan / Analisis permintaan / Buat penawaran: JSON sekali jalan.\nUntuk Chatbot, pilih pesanan di sidebar untuk diskusi pesanan itu.",
        "Pilih mod Ejen di kanan, kemudian sembang:\n• Chatbot: Soal jawab; konteks pesanan pilihan.\n• Plan-Execute-Replan / B2B Coordinator / Trade Assistant: ejen strim.\n• Cadang / Cari / Terjemah / Analisis pertanyaan / Jana sebut harga: JSON sekali gus.\nUntuk Chatbot, pilih pesanan dalam sidebar untuk bincang pesanan itu.",
    ),
    "Generates a quotation draft from inquiry products and requirements.\nDraft is advisory only — enter official amount and validity in the form below before submitting.": (
        "Membuat draf penawaran dari produk dan persyaratan permintaan.\nDraf hanya bersifat advisory — masukkan jumlah resmi dan validitas di formulir bawah sebelum kirim.",
        "Menjana draf sebut harga daripada produk dan keperluan pertanyaan.\nDraf hanya nasihat — masukkan jumlah rasmi dan tempoh sah dalam borang di bawah sebelum hantar.",
    ),
    "Product AI translate": ("Terjemahan AI Produk", "Terjemah AI Produk"),
    "Import AI column mapping": ("Impor pemetaan kolom AI", "Import pemetaan lajur AI"),
    "New Stock": ("Stok Baru", "Stok Baharu"),
    "Adjustment Type": ("Tipe Penyesuaian", "Jenis Pelarasan"),
    "Unit Value": ("Nilai Satuan", "Nilai Unit"),
    "Adjustment Tipe": ("Tipe Penyesuaian", "Jenis Pelarasan"),
    "Baru Stock": ("Stok Baru", "Stok Baharu"),
    "Unit Nilai": ("Nilai Satuan", "Nilai Unit"),
}

def main() -> None:
    out = {en: {"id": id_v, "ms": ms_v} for en, (id_v, ms_v) in TRANSLATIONS.items()}
    path = Path(__file__).resolve().parent / "i18n_admin_phrases_id_ms.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(out)} phrases to {path}")

if __name__ == "__main__":
    main()
