#!/usr/bin/env python3
"""Generate complete vi/admin.json from en structure with manual Vietnamese translations."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "frontend" / "i18n"
CACHE_PATH = Path(__file__).resolve().parent / "i18n-translation-cache.json"

OVERRIDES = {
    "admin.brand": "Quản trị CandyPro",
    "admin.langLabel": "VI",
    "admin.langLabelShort": "VI",
    "admin.langTitle": "Tiếng Việt",
    "admin.users.showing": "Hiển thị {from} đến {to} trong tổng số {total} kết quả",
    "admin.staff.showing": "Hiển thị {from} đến {to} trong tổng số {total} kết quả",
    "admin.auditLog.showing": "Hiển thị {from} đến {to} trong tổng số {total} kết quả",
    "admin.inventory.batch_edit_result": "Đã cập nhật {updated}, {errors} lỗi",
    "admin.products.base_price": "Giá cơ bản (USD)",
    "admin.products.field_energy_kcal": "Năng lượng (kcal)",
}

COMMON = {
    "cancel": "Hủy",
    "save": "Lưu",
    "edit": "Sửa",
    "delete": "Xóa",
    "create": "Tạo",
    "update": "Cập nhật",
    "loading": "Đang tải...",
    "saving": "Đang lưu...",
    "creating": "Đang tạo...",
    "updating": "Đang cập nhật...",
    "actions": "Thao tác",
    "status": "Trạng thái",
    "name": "Tên",
    "email": "Email",
    "phone": "Điện thoại",
    "company": "Công ty",
    "role": "Vai trò",
    "notes": "Ghi chú",
    "date": "Ngày",
    "amount": "Số tiền",
    "currency": "Tiền tệ",
    "total": "Tổng",
    "search": "Tìm kiếm",
    "filter": "Lọc",
    "export": "Xuất",
    "import": "Nhập",
    "view": "Xem",
    "previous": "Trước",
    "next": "Tiếp",
    "confirm": "Xác nhận",
    "approve": "Phê duyệt",
    "reject": "Từ chối",
    "refund": "Hoàn tiền",
    "send": "Gửi",
    "active": "Hoạt động",
    "inactive": "Không hoạt động",
    "pending": "Chờ xử lý",
    "paid": "Đã thanh toán",
    "draft": "Bản nháp",
    "confirmed": "Đã xác nhận",
    "completed": "Hoàn tất",
    "cancelled": "Đã hủy",
    "description": "Mô tả",
    "title": "Tiêu đề",
    "type": "Loại",
    "code": "Mã",
    "value": "Giá trị",
    "balance": "Số dư",
    "yes": "Có",
    "no": "Không",
    "success": "Thành công",
    "failed": "Thất bại",
    "error": "Lỗi",
    "all": "Tất cả",
    "none": "Không có",
    "remove": "Xóa",
    "add": "Thêm",
    "close": "Đóng",
    "back": "Quay lại",
    "print": "In",
    "loading_details": "Đang tải chi tiết...",
    "no_data": "Không có dữ liệu.",
    "showing": "Hiển thị {from}–{to} / {total}",
    "col_status": "Trạng thái",
    "col_name": "Tên",
    "col_actions": "Thao tác",
    "col_amount": "Số tiền",
    "col_date": "Ngày",
    "col_type": "Loại",
    "col_created": "Ngày tạo",
    "col_customer": "Khách hàng",
    "col_product": "Sản phẩm",
    "col_order": "Đơn hàng",
    "col_email": "Email",
    "col_id": "ID",
    "col_time": "Thời gian",
    "col_user": "Người dùng",
    "col_role": "Vai trò",
    "status_updated": "Đã cập nhật trạng thái thành công.",
    "confirm_delete": "Xác nhận xóa?",
    "load_failed": "Không thể tải dữ liệu.",
    "save_failed": "Lưu thất bại.",
    "created_success": "Tạo thành công.",
    "updated_success": "Cập nhật thành công.",
    "deleted_success": "Xóa thành công.",
}

SECTIONS: dict[str, dict[str, str]] = {
    "nav": {
        "dashboard": "Bảng điều khiển",
        "users": "Người dùng",
        "inquiries": "Yêu cầu báo giá",
        "orders": "Đơn hàng",
        "returns": "Trả hàng",
        "products": "Sản phẩm",
        "categories": "Danh mục",
        "companies": "Doanh nghiệp",
        "trades": "Giao dịch thương mại",
        "pricing": "Giá",
        "oemProjects": "Dự án OEM",
        "content": "Nội dung",
        "inventory": "Kho hàng",
        "xlsx": "Công cụ XLSX",
        "shipments": "Vận chuyển",
        "invoices": "Hóa đơn",
        "management": "Quản lý",
        "superadmin": "Siêu quản trị viên",
        "analytics": "Phân tích",
        "financial": "Tài chính",
        "certifications": "Chứng nhận",
        "staff": "Nhân viên",
        "auditLog": "Nhật ký kiểm toán",
        "settings": "Cài đặt",
        "translations": "Bản dịch",
        "ai": "Ứng dụng AI",
        "organizations": "Tổ chức mua hàng",
        "channels": "Kênh bán",
        "webhooks": "Webhooks",
        "hooks": "Hook & Sự kiện",
        "coupons": "Phiếu giảm giá",
        "shipping_rates": "Vận chuyển & Thuế",
        "tax_rates": "Thuế suất",
    },
    "dashboard": {
        "title": "Bảng điều khiển",
        "subtitle": "Tổng quan nền tảng và các chỉ số chính.",
        "loading": "Đang tải thống kê bảng điều khiển...",
        "error": "Lỗi tải bảng điều khiển",
        "total_users": "Tổng người dùng",
        "total_orders": "Tổng đơn hàng",
        "total_inquiries": "Tổng yêu cầu báo giá",
        "total_revenue": "Tổng doanh thu",
        "this_week": "tuần này",
        "new_users_this_week": "{count} mới tuần này",
        "pending": "chờ xử lý",
        "recent_activity": "Hoạt động gần đây",
        "col_activity": "Hoạt động",
        "no_activity": "Không có hoạt động gần đây",
        "revenue_this_month": "Doanh thu tháng này",
        "active_customers": "Khách hàng hoạt động",
        "avg_order_value": "Giá trị đơn hàng TB",
        "conversion_rate": "Tỷ lệ chuyển đổi",
        "revenue_chart": "Doanh thu (30 ngày)",
        "revenue": "Doanh thu",
        "activity_order": "Khách hàng {user} đặt đơn {order_no}",
        "activity_inquiry": "Nhận yêu cầu B2B mới từ {company}",
        "activity_user": "Người dùng mới đăng ký: {user}",
        "unknown_customer": "Khách hàng không xác định",
        "unknown_company": "Doanh nghiệp không xác định",
        "unknown_user": "Người dùng không xác định",
        "time_just_now": "Vừa xong",
        "time_minutes_ago": "{count} phút trước",
        "time_hours_ago": "{count} giờ trước",
        "time_days_ago": "{count} ngày trước",
        "time_unknown": "Không xác định",
    },
    "status_options": {
        "draft": "Bản nháp",
        "sent": "Đã gửi",
        "paid": "Đã thanh toán",
        "overdue": "Quá hạn",
        "cancelled": "Đã hủy",
        "active": "Hoạt động",
        "inactive": "Không hoạt động",
    },
    "shippingRates": {
        "title": "Biểu phí vận chuyển",
        "description": "Bảng cước theo điểm đến. Số ngày ước tính chỉ mang tính tham khảo báo giá — không phải cam kết thời gian vận chuyển.",
        "create": "Thêm biểu phí",
        "no_data": "Chưa có biểu phí vận chuyển.",
        "destination": "Điểm đến",
        "carrier": "Hãng vận chuyển",
        "min_weight": "Trọng lượng tối thiểu (kg)",
        "max_weight": "Trọng lượng tối đa (kg)",
        "base_cost": "Phí cơ bản",
        "cost_per_kg": "Phí theo kg",
        "estimated_days": "Số ngày ước tính",
        "estimated_days_hint": "Thời gian vận chuyển tham khảo cho báo giá nội bộ. Có thể thay đổi; xác nhận khi đặt hàng.",
        "col_destination": "Điểm đến",
        "col_carrier": "Hãng vận chuyển",
        "col_base_cost": "Phí cơ bản",
        "col_days": "Số ngày",
    },
    "taxRates": {
        "title": "Thuế suất",
        "description": "Thuế suất theo quốc gia/vùng áp dụng khi thanh toán giỏ hàng.",
        "create": "Thêm thuế suất",
        "no_data": "Chưa cấu hình thuế suất.",
        "country": "Quốc gia (ISO)",
        "region": "Vùng / Bang",
        "rate": "Thuế suất",
        "rate_hint": "Phân số thập phân, vd. 0,08875 = 8,875%",
        "col_country": "Quốc gia",
        "col_region": "Vùng",
        "col_rate": "Thuế suất",
    },
    "coupons": {
        "title": "Phiếu giảm giá & Thẻ quà tặng",
        "description": "Mã khuyến mãi và tín dụng trả trước.",
        "create": "Tạo phiếu giảm giá",
        "create_giftcard": "Tạo thẻ quà tặng",
        "tab_coupons": "Phiếu giảm giá",
        "tab_giftcards": "Thẻ quà tặng",
        "no_data": "Chưa có phiếu giảm giá.",
        "no_giftcards": "Chưa có thẻ quà tặng.",
        "code": "Mã",
        "min_order": "Đơn tối thiểu",
        "starts_at": "Bắt đầu",
        "expires_at": "Hết hạn",
        "type_percentage": "Phần trăm",
        "type_fixed": "Số tiền cố định",
        "col_code": "Mã",
        "col_used": "Đã dùng",
        "col_initial": "Ban đầu",
        "col_balance": "Số dư",
        "showing": "{total} tổng cộng",
    },
    "categories": {
        "title": "Danh mục",
        "description": "Quản lý danh mục sản phẩm với tên, bí danh và mô tả đa ngôn ngữ.",
        "add_category": "Thêm danh mục",
        "edit_category": "Sửa danh mục",
        "create_category": "Tạo danh mục",
        "col_slug": "Slug",
        "col_products": "Sản phẩm",
        "no_data": "Không tìm thấy danh mục",
        "slug": "Slug",
        "icon": "Biểu tượng",
        "thumbnail": "URL ảnh thu nhỏ",
        "translations_label": "Bản dịch",
        "translations_hint": "Tên, bí danh và mô tả danh mục chỉ được quản lý tại đây. Tiếng Trung là locale nguồn.",
        "field_name": "Tên",
        "field_alias": "Bí danh",
        "field_description": "Mô tả",
        "name_required": "Tên danh mục tiếng Trung là bắt buộc",
        "slug_required": "Slug là bắt buộc",
        "confirm_delete": "Xóa danh mục này?",
        "created_success": "Đã tạo danh mục",
        "updated_success": "Đã cập nhật danh mục",
        "deleted_success": "Đã xóa danh mục",
    },
    "inventory": {
        "title": "Kho hàng",
        "description": "Theo dõi và quản lý tồn kho, giá trị và điều chỉnh sản phẩm.",
        "adjust_stock": "Điều chỉnh tồn kho",
        "total_products": "Tổng sản phẩm",
        "low_stock": "Tồn kho thấp",
        "out_of_stock": "Hết hàng",
        "in_stock": "Còn hàng",
        "total_value": "Tổng giá trị",
        "search": "Tìm theo tên sản phẩm hoặc SKU...",
        "filter_stock": "Lọc theo trạng thái tồn kho",
        "filter_category": "Lọc theo danh mục",
        "filter_all": "Tất cả tồn kho",
        "filter_low": "Tồn kho thấp",
        "filter_out": "Hết hàng",
        "filter_in": "Còn hàng",
        "all_categories": "Tất cả danh mục",
        "col_category": "Danh mục",
        "col_sku": "SKU",
        "col_stock": "Tồn kho",
        "col_moq": "MOQ",
        "col_unit_value": "Giá trị đơn vị",
        "col_total_value": "Tổng giá trị",
        "loading": "Đang tải kho hàng...",
        "no_data": "Không có dữ liệu kho hàng.",
        "history": "Lịch sử",
        "adjust_title": "Điều chỉnh tồn kho",
        "current_stock": "Tồn kho hiện tại",
        "new_stock": "Tồn kho mới",
        "adjustment_type": "Loại điều chỉnh",
        "type_set": "Đặt thành",
        "type_add": "Cộng thêm",
        "type_subtract": "Trừ bớt",
        "reason": "Lý do",
        "reason_restock": "Nhập hàng",
        "reason_correction": "Hiệu chỉnh",
        "reason_damage": "Hư hỏng/Mất mát",
        "reason_return": "Khách trả hàng",
        "reason_audit": "Kiểm kê",
        "reason_other": "Khác",
        "history_title": "Lịch sử tồn kho",
        "from_to": "{from} → {to}",
        "no_history": "Không có lịch sử điều chỉnh.",
        "select_all": "Chọn tất cả",
        "selected_count": "Đã chọn {count}",
        "export_selected": "Xuất mục đã chọn",
        "import_xlsx": "Nhập XLSX",
        "import_title": "Nhập sản phẩm từ XLSX",
        "import_drop_zone": "Nhấp hoặc kéo thả file XLSX vào đây",
        "import_preview": "Xem trước dữ liệu nhập",
        "import_apply": "Áp dụng nhập",
        "import_applying": "Đang nhập...",
        "import_column_mapping": "Ánh xạ cột",
        "import_ai_mapping": "Ánh xạ do AI đề xuất",
        "import_image_detected": "Phát hiện URL ảnh — sẽ tự động tải lên khi nhập",
        "import_created": "Đã tạo",
        "import_updated": "Đã cập nhật",
        "import_errors": "Lỗi",
        "import_select_file": "Vui lòng chọn file XLSX",
        "import_download_template": "Tải mẫu",
        "import_result": "Nhập xong: {created} tạo mới, {updated} cập nhật, {errors} lỗi",
        "select_rows_to_export": "Chọn mục để xuất",
        "clear_filters": "Xóa bộ lọc",
        "clear_selection": "Bỏ chọn",
        "import_parsing": "Đang phân tích file...",
        "batch_edit": "Sửa hàng loạt",
        "batch_edit_title": "Sửa hàng loạt sản phẩm",
        "batch_edit_selected_count": "Đang sửa {count} sản phẩm",
        "batch_edit_field": "Trường",
        "batch_edit_value": "Giá trị",
        "batch_edit_apply": "Áp dụng thay đổi",
        "batch_edit_applying": "Đang áp dụng...",
        "batch_edit_select_field": "Chọn trường...",
        "batch_edit_field_category": "Danh mục",
        "batch_edit_field_categorySlug": "Slug danh mục",
        "batch_edit_field_status": "Trạng thái",
        "batch_edit_field_stockQuantity": "Số lượng tồn kho",
        "batch_edit_field_basePrice": "Giá cơ bản",
        "batch_edit_field_moq": "MOQ",
        "batch_edit_field_leadTime": "Thời gian giao hàng",
        "batch_edit_field_halalCertified": "Chứng nhận Halal",
        "batch_edit_field_oemAvailable": "Hỗ trợ OEM",
        "batch_edit_field_hsCode": "Mã HS",
        "batch_edit_field_shelfLife": "Hạn sử dụng",
        "batch_edit_field_storage": "Bảo quản",
        "batch_delete": "Xóa hàng loạt",
        "batch_delete_title": "Xác nhận xóa hàng loạt",
        "batch_delete_confirm": "Bạn có chắc muốn xóa {count} sản phẩm đã chọn? Thao tác này không thể hoàn tác.",
        "batch_delete_applying": "Đang xóa...",
        "batch_delete_result": "{deleted} đã xóa, {errors} lỗi",
        "import_preview_more": "... và {n} dòng nữa",
        "export_filename": "inventory",
        "csv_headers": "SKU,Tên sản phẩm,Tồn kho,Tồn tối thiểu,Trạng thái,Vị trí,Lô,Hạn dùng",
        "tab_stock": "Tồn kho",
        "tab_warehouses": "Kho",
        "tab_transfers": "Điều chuyển",
        "add_warehouse": "Thêm kho",
        "no_warehouses": "Chưa có kho.",
        "no_transfers": "Chưa có điều chuyển.",
        "wh_id": "ID kho",
        "wh_code": "Mã",
        "wh_name": "Tên",
        "wh_country": "Quốc gia",
        "update_stock": "Cập nhật tồn kho",
        "create_transfer": "Tạo điều chuyển",
        "transfer_no": "Số điều chuyển",
        "from_wh": "Từ kho",
        "to_wh": "Đến kho",
        "product_id": "ID sản phẩm",
        "qty": "Số lượng",
    },
    "products": {
        "title": "Sản phẩm",
        "description": "Quản lý danh mục sản phẩm với đầy đủ thao tác CRUD.",
        "add_product": "Thêm sản phẩm",
        "batch_translate": "Dịch locale còn thiếu",
        "translating": "Đang dịch…",
        "search_placeholder": "Tìm theo tên sản phẩm hoặc SKU...",
        "status_filter": "Trạng thái",
        "status_published": "Đã xuất bản (mặc định)",
        "status_all": "Tất cả trạng thái",
        "status_draft": "Bản nháp",
        "status_inactive": "Không hoạt động",
        "loading": "Đang tải sản phẩm...",
        "no_data": "Không tìm thấy sản phẩm.",
        "col_category": "Danh mục",
        "col_moq": "MOQ",
        "col_stock": "Tồn kho",
        "edit_product": "Sửa sản phẩm",
        "create_product": "Tạo sản phẩm",
        "slug": "Slug",
        "alias": "Bí danh",
        "category": "Danh mục",
        "category_slug": "Slug danh mục",
        "category_alias": "Bí danh danh mục",
        "moq": "MOQ",
        "lead_time": "Thời gian giao hàng",
        "lead_time_hint": "Nhập sau khi bộ phận bán hàng xác minh để hiển thị trên catalog. Có thể ghi cụ thể (vd. \"25 ngày làm việc sau xác nhận đơn\") — không dùng mô tả mơ hồ như \"khoảng X tuần\". Để trống hoặc dùng \"xác nhận khi đặt hàng\" cho đến khi xác minh.",
        "stock_quantity": "Số lượng tồn kho",
        "oem": "OEM",
        "halal": "Halal",
        "featured": "Nổi bật",
        "summary": "Tóm tắt",
        "description_label": "Mô tả",
        "thumbnail": "Ảnh thu nhỏ",
        "og_image": "Ảnh OG (Chia sẻ mạng xã hội)",
        "og_image_hint": "Tùy chọn. Ghi đè ảnh thu nhỏ cho Facebook/LinkedIn. Khuyến nghị 1200×630.",
        "upload_image": "Tải ảnh lên",
        "upload_images": "Tải ảnh lên",
        "images": "Ảnh (phân tách bằng dấu phẩy)",
        "flavors": "Hương vị (phân tách bằng dấu phẩy)",
        "shapes": "Hình dạng (phân tách bằng dấu phẩy)",
        "certifications": "Chứng nhận (phân tách bằng dấu phẩy)",
        "ingredients": "Thành phần",
        "allergens": "Dị ứng",
        "shelf_life": "Hạn sử dụng",
        "storage": "Bảo quản",
        "name_required": "Tên sản phẩm là bắt buộc.",
        "confirm_delete": "Xóa sản phẩm này?",
        "section_weight": "Trọng lượng & Đo lường",
        "section_dimensions": "Kích thước sản phẩm (mm)",
        "section_dietary": "Nhãn dinh dưỡng",
        "section_nutrition": "Dinh dưỡng (trên 100g)",
        "section_compliance": "Tuân thủ thành phần",
        "section_trade": "Thương mại & Đóng gói",
        "section_sample": "Thông số mẫu",
        "field_net_weight_per_piece": "Trọng lượng tịnh/miếng (g)",
        "field_net_weight_per_pack": "Trọng lượng tịnh/gói (g)",
        "field_gross_weight_per_carton": "Trọng lượng tổng/thùng (kg)",
        "field_pieces_per_pack": "Miếng/gói",
        "field_packs_per_carton": "Gói/thùng",
        "field_length_mm": "Chiều dài (mm)",
        "field_width_mm": "Chiều rộng (mm)",
        "field_height_mm": "Chiều cao (mm)",
        "field_vegan": "Thuần chay",
        "field_gluten_free": "Không gluten",
        "field_sugar_free": "Không đường",
        "field_kosher": "Kosher",
        "field_organic": "Hữu cơ",
        "field_energy_kj": "Năng lượng (kJ)",
        "field_fat_g": "Chất béo (g)",
        "field_saturated_fat_g": "Chất béo bão hòa (g)",
        "field_carbohydrates_g": "Carbohydrate (g)",
        "field_sugars_g": "Đường (g)",
        "field_protein_g": "Protein (g)",
        "field_salt_g": "Muối (g)",
        "field_fiber_g": "Chất xơ (g)",
        "field_additives": "Phụ gia (số E)",
        "field_sweetener_type": "Loại chất ngọt",
        "field_cocoa_solids_pct": "% Chất rắn cacao",
        "field_milk_solids_pct": "% Chất rắn sữa",
        "field_gmo_status": "Trạng thái GMO",
        "field_may_contain": "Có thể chứa",
        "field_water_activity": "Hoạt độ nước (aʷ)",
        "field_gtin": "GTIN / Mã vạch",
        "field_hs_code": "Mã HS",
        "field_primary_packaging": "Bao bì chính",
        "field_inner_pack_config": "Cấu hình gói trong",
        "field_pallet_config": "Cấu hình pallet",
        "field_sample_moq": "MOQ mẫu",
        "field_sample_lead_time": "Thời gian mẫu",
        "field_sample_lead_time_hint": "Thời gian mẫu tham khảo — xác nhận bởi bộ phận bán hàng trong báo giá mẫu; không dùng \"khoảng X tuần\".",
        "field_sample_price": "Giá mẫu",
        "packaging_placeholder": "flow-wrap, foil, box, bag, jar",
        "inner_pack_placeholder": "vd. 12 đơn vị/hộp trưng bày",
        "pallet_config_placeholder": "vd. 48 thùng/lớp × 5 lớp",
        "gmo_option_gmo": "GMO",
        "gmo_option_non_gmo": "Non-GMO",
        "gmo_option_gmo_free_certified": "GMO-Free Certified",
        "translations_label": "Bản dịch",
        "translations_hint": "Mọi nội dung hướng khách hàng chỉ quản lý tại đây. Tiếng Trung là locale nguồn; trường scalar đồng bộ khi lưu.",
        "locale_tab_en": "English",
        "locale_tab_zh": "Chinese",
        "locale_tab_ar": "Arabic",
        "locale_tab_ko": "Korean",
        "locale_tab_ja": "Japanese",
        "locale_tab_zh-tw": "Traditional Chinese",
        "locale_tab_th": "Thai",
        "locale_tab_vi": "Vietnamese",
        "locale_tab_id": "Indonesian",
        "locale_tab_ms": "Malay",
        "trans_name_placeholder": "Để trống để dùng tên mặc định",
        "ai_translate": "Dịch tất cả bằng AI",
        "ai_translating": "Đang dịch...",
        "ai_translate_done": "Đã lưu bản dịch thành công",
        "ai_translate_reloaded": "Dịch hoàn tất trên máy chủ; đã tải bản dịch mới nhất từ cơ sở dữ liệu",
        "ai_generate": "Tạo bằng AI",
        "ai_generating": "Đang tạo dữ liệu sản phẩm...",
        "ai_description_label": "Mô tả sản phẩm của bạn",
        "ai_description_placeholder": "vd. Thanh socola sữa 150g có hạnh nhân, thuần chay, hạn 12 tháng, bọc flow-wrap từng miếng, 24 miếng/hộp trưng bày, chứng nhận halal...",
        "ai_language_label": "Ngôn ngữ nguồn",
        "ai_empty_preview": "Nhập mô tả sản phẩm bên trái và nhấn Tạo để xem các trường AI điền tại đây.",
        "ai_section_basic": "Thông tin cơ bản",
        "ai_section_weight": "Trọng lượng & Đo lường",
        "ai_section_dimensions": "Kích thước",
        "ai_section_nutrition": "Dinh dưỡng (trên 100g)",
        "ai_section_compliance": "Tuân thủ thành phần",
        "ai_section_trade": "Thương mại & Đóng gói",
        "ai_section_dietary": "Nhãn dinh dưỡng",
        "ai_section_sample": "Thông số mẫu",
        "ai_save": "Lưu sản phẩm",
        "ai_import": "Nhập AI",
        "ai_generate_failed": "Tạo AI thất bại. Hãy thử mô tả chi tiết hơn.",
        "section_market": "Hồ sơ thị trường",
        "section_cost_stack": "Cơ cấu chi phí",
        "market_code": "Mã thị trường",
        "label_template": "ID mẫu nhãn",
        "destination_countries": "Quốc gia đích",
        "required_certs": "Từ khóa chứng nhận bắt buộc",
        "csv_hint": "Phân tách bằng dấu phẩy",
        "save_market_profile": "Lưu hồ sơ thị trường",
        "reload_market": "Tải lại",
        "save_cost_stack": "Lưu cơ cấu chi phí",
        "market_saved": "Đã lưu hồ sơ thị trường.",
        "cost_saved": "Đã lưu cơ cấu chi phí.",
        "market_load_failed": "Không thể tải dữ liệu thị trường.",
        "cost_material": "Nguyên liệu",
        "cost_labor": "Nhân công",
        "cost_logistics": "Logistics",
        "ai_translate_slow": "Dịch đang lâu hơn bình thường. Vui lòng đợi hoặc thử lại sau.",
    },
}

# Load extended phrase map from companion JSON if present
PHRASES_PATH = Path(__file__).resolve().parent / "vi_admin_phrases.json"
if PHRASES_PATH.exists():
    PHRASES: dict[str, str] = json.loads(PHRASES_PATH.read_text(encoding="utf-8"))
else:
    PHRASES = {}


def flatten(obj: dict, prefix: str = "") -> dict[str, str]:
    out: dict[str, str] = {}
    for key, value in obj.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            out.update(flatten(value, path))
        else:
            out[path] = value
    return out


def unflatten(flat: dict[str, str]) -> dict:
    root: dict = {}
    for path, value in flat.items():
        parts = path.split(".")
        cur = root
        for part in parts[:-1]:
            cur = cur.setdefault(part, {})
        cur[parts[-1]] = value
    return root


def has_vietnamese(text: str) -> bool:
    return bool(re.search(r"[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ]", text, re.I))


def has_chinese(text: str) -> bool:
    return bool(re.search(r"[\u4e00-\u9fff]", text))


def translate_key(key: str, en_val: str, cache: dict[str, str]) -> str:
    if key in OVERRIDES:
        return OVERRIDES[key]
    if key in PHRASES:
        return PHRASES[key]
    if en_val in PHRASES:
        return PHRASES[en_val]

    parts = key.split(".")
    if len(parts) >= 3 and parts[0] == "admin":
        section, field = parts[1], parts[-1]
        if section in SECTIONS and field in SECTIONS[section]:
            return SECTIONS[section][field]
        if field in COMMON:
            return COMMON[field]

    if en_val in COMMON:
        return COMMON[en_val]

    cached = cache.get(en_val, en_val)
    if cached != en_val and has_vietnamese(cached) and not has_chinese(cached):
        return cached

    return en_val


def main() -> None:
    cache = json.loads(CACHE_PATH.read_text(encoding="utf-8")).get("vi", {})
    en_flat = flatten(json.loads((ROOT / "en" / "admin.json").read_text(encoding="utf-8")))
    out_flat = {key: translate_key(key, val, cache) for key, val in en_flat.items()}

    out_path = ROOT / "vi" / "admin.json"
    out_path.write_text(json.dumps(unflatten(out_flat), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    untranslated = sum(
        1 for k, v in out_flat.items()
        if v == en_flat[k] and re.search(r"[A-Za-z]{3,}", v) and not re.fullmatch(r"[A-Z0-9/\\s&+×→.:{}$#%-]+", v)
    )
    chinese = sum(1 for v in out_flat.values() if has_chinese(v))
    print(f"Wrote {out_path} — untranslated={untranslated}, chinese={chinese}, keys={len(out_flat)}")


if __name__ == "__main__":
    main()
